@startuml



|用户|
start
:发起付款请求;

|支付|
:发起支付请求;

|优惠|
|用户|
:付款;


|支付|
:通知订单;

|订单|
:保存付款记录;
:更新订单状态为有效待分配;
:占用库存;

|订单|
if (是否有推荐返利的券) then (true)
     |优惠|
     :发放推荐返利积分;
endif

|订单|
if (是否要领取合作码) then (true)
     |优惠|
     :领取合作码;
endif

|订单|
if (是否要通知Seer) then (true)
     |订单|
     :通知Sear;
endif

|订单|
if (是否是抢购订单) then (true)
     |订单|
     :修改抢购Reids订单状态;
endif

|订单|
:记录操作日志;

stop
@enduml

