    @startuml



|用户|
start
:取消订单;
|支付|
|WMS|
|库存|
|订单|
if(是否推送到WMS) then(true)
  |WMS|
  :取消订单;
endif


|订单|
if (是否支付或者 是否为 0元单) then (true)
   |库存|
   :释放占用;
else
 |库存|
 :释放预扣;

endif


|订单|
if (是否支付) then (true)
   |订单|
   :作废发票;
   |支付|
   :生成退款单;
endif

|订单|
if (是否有券且未支付) then (true)
   |订单|
   :返还券;
   :返还邀请码;
endif

if (是否有券且未支付) then (true)
   |订单|
   :返还券;
   :返还邀请码;
endif

|订单|
:更新订单状态为已取消;
:通知抢购系统回收库存;
:增加操作日志;

stop

@enduml