
@startuml


|用户|
start
:提交订单;

|订单|
if(参数异常 && 业务异常) then (是)
    :通知抢购回收库存;
    stop;
endif

:读取用户信息和地址新;
if(Cookie地址与Db地址不一致)
    stop;
endif

:构造订单主表;
:构造用户信息;
:构造订单地址;
:构造订单金额;

if(判断是否为黄牛) then(是)
    :标记黄牛;
    :更新结束阶段为Cancelled;
else (否)
    :更新付款阶段为Paid;
    :更新物流阶段为Ready;
endif

if(检查订单是否同步过)then(是)
    stop;
endif

|优惠|
:算价并使用券;
|订单|
:根据优惠结果更新订单;

:保存订单主表;
:保存发票;
:保存地址;
:保存商品;
:保存发货单;

if(黄牛订单)then(是)
    :通知抢购系统回收库存;
endif;

:发送邮件;

stop
@enduml

