
@startuml
|订单|
start
:读取订单号;
:读取订单;
:系统审核;

if(审核结果)then(黄牛)
    stop
endif

|订单|
:保存订单#1;
:广播订单状态与信息;
 fork
|订单|
:增加操作日志;
fork again
:发送邮件;
fork again
:发送短信;


end fork
stop
@enduml

#1 核心内容：生成订单项，生成发票，生成发货单;

#2 0元单需要人工审核。
