@startuml

|用户|
start
:发起付款请求;

|支付|
:支付审核;
:生成付款请求;

|用户|
:付款;

|支付|
:通知付款Complete;

|订单|
:增加或更新付款记录;

if(增加付款记录) then
    if(是不是多笔付款)then(是)
        :标记重复付款;
        :标记订单重复付款;
        stop;
    endif

else (更新付款记录)
        |WMS|
        :取消Hold发货单;
        |订单|
        :取消挂起订单;
endif

if(是否已经支付)then(是)
    stop;
endif

:占用库存;
:更新订单的付款阶段为paid;
:修改订单的物流阶段状态为Ready;
:广播订单状态与信息;

fork

|订单|
:通知Sear;
fork again
if(订单类型) then(抢购订单)
    :修改抢购订单的Redis状态;
endif
fork again
:记录操作日志;
fork again
:发送邮件;
fork again
:调用优惠领取推荐返利积分;
fork again
:调用优惠领取合作码;
end fork

stop
@enduml

可能会收到多笔支付，订单会记录，而且会标记，便于查询。

如果是海外支付，根据付款通知的uuid来判断是会否是重复的通知。
如果是国内支付，根据付款通知的网关流水号来判断。



