@startuml

|WMS|
|库存|
|订单|
start
:读取订单;
if(订单类型)then (普通订单)
    |订单|
    if(是否有库存信息) then (否)
        |库存|
       :路由库存;
       :预扣库存;
    endif
endif


|订单|
if(订单地址)then (印度)
    |WMS|
    :计算商品税费;
    |订单|
    :更新订单税费;
endif
|订单|
:推送到WMS#1;


|订单|
:更新订单为已推送;
:广播订单状态与信息;
stop
@enduml


#1 推送到WMS的时候，包含订单金额信息，发货单信息。订单金额信息给ERPADMIN，发货单信息给WMS。
印度：计算订单金额信息时回调用wms的税费接口计算商品税额。