@startuml

|库存|
|优惠|
|客服|
start
:取消转已付款;
|订单|
if(订单类型)then(普通订单)
|库存|
:路由库存;
:预扣库存;
:占用库存;
|订单|
:更新路由信息;
:增加发货单;
endif

|订单|
:修改订单的付款阶段状态为Paid;
:修改订单的物流阶段状态为Ready;
:清空结束阶段状态;
:增加操作日志;
stop
@enduml
订单取消后，如果继续收到付款消息，虽然保存了付款金额，此时订单不会继续执行。此时需要将订单转为已支付状态。
抢购单和第三方订单 不用重新路由、预扣和占用。