@startuml

|用户|

start
:修改订单的收货地址;
|库存|
|订单|
if(地址可修改) then(false)
    stop;
endif;
if(是否需要重新路由) then(true)
        |库存|
        :重新预扣库存;
        :保存路由信息;
        :增加新的发货单，并取消老发货单;
endif;

:修改订单地址;


stop
@enduml

支付之前可以修改地址，支付之后不能修改地址。

抢购单不用重新路由。
如果不修改省市区街道，可以不用路由。

