@startuml


|用户|
start
:签收包裹;
 |优惠|
|WMS|
:通知包裹拒收入库;

|订单|
:更新包裹状态为已拒收和拒收时间;
:计算订单商品履约日志;
:计算订单IMEI履约日志;
:生成退款单;
:增加操作日志;


if(是否所有包裹都结束) then(true)
    |订单|
    :更新订单状态;
'    :更新发票信息;
    if(是否至少签收1个) then(是)
        |订单|
        :增加积分;
        if(是否有邀请码)then (true)
            |优惠|
            :裂变邀请码;
         |订单|
        endif
        if(是否为10085订单) then (true)
            |订单|
            :通知10085订单已签收;
        endif

    else (否)
        |订单|
        if (是否为10085订单) then (true)
            |订单|
            :通知10085订单已拒收;
        endif

    endif

endif






stop
@enduml