@startuml
state ordercenter {
    state 支付状态 {
        [*] -down-> 未支付
        [*] -left-> 无需支付
        未支付 --> 已支付 : 付款
    }
    state 订单状态 {
        待发货 -down-> 已出库 : scm通知已发货
        已出库 -left-> 已签收 : scm通知已签收
        已出库 -down-> 已拒收 : scm通知已拒收
        待发货 -left-> 已取消 : 订单取消
    }

    state 库存状态{
        [*] --> 待预扣 : 抢购订单
        [*] --> 已预扣 : 普通订单
        已预扣 --> 已占用 : 订单支付成功
    }

    state 锁定状态{
        [*] --> 未锁定
        未锁定 --> 已锁定 : 订单锁定
        已锁定 --> 未锁定 : 订单解锁
    }

    state 推送状态{
        [*] --> 未推送
        未推送 --> 已推送 : 订单推送至scm 成功
        未推送 --> 推送失败 : 订单推送至scm 失败
    }

}

state scm {
    [*] -right-> 已分配实存 : 实存分配
    已分配实存 --> 已发货 : 订单出库
    已发货 --> 签收 : 签收
    已发货 --> 拒收 : 拒收
    已分配实存 ---> ordercenter : 通知出库
    已发货 ---> ordercenter : 通知出库
    签收 --> ordercenter : 通知已签收
    拒收 --> ordercenter : 通知已拒收
}

@enduml