@startuml
'此文档描述订单相关的业务用例
left to right direction
skinparam packageStyle rectangle

:个人用户: as User
:运营人员: as Operator
:物流人员: as Logistics

rectangle 订单 {
    User --> (下订单)
    User -> (支付)
    User -> (查看订单)
    User -> (下载发票)
    User -> (取消订单)
    User -> (查看路由)
    User -> (申请售后)

    Operator --> (查看订单)
    Operator -> (修改订单)

    (取消订单) --> (取消未支付订单)
    (取消订单) --> (取消已支付订单)
    (申请售后) --> (申请退货)
    (申请售后) --> (申请换货)
}

rectangle 仓储物流 {
    Logistics --> (查看发货单)
    Logistics --> (发货)
    Logistics --> (打印发票)
    Logistics --> (逆向收货)
    Logistics --> (包裹拒收)

    (发货)-->(分配库存)
    (发货)-->(推送第三方)
    (发货)-->(第三方发货)
}

@enduml