@startuml

actor 用户

用户 -> 订单中心: 创建换货受理单
订单中心 -> GSP: 通知GSP\n 1.受理单核心信息\n 2.受理单 Item\n 3.受理单地址
GSP -> GSP:创建处理单(已提交)

GSP -> GSP:审核处理单(已审核/已取消)
alt 审核取消
    GSP --> 订单中心: 通知订单中心取消受理单
    订单中心 --> 订单中心: 取消受理单
else 审核通过
    GSP --> 订单中心: 通知订单中心审核通过受理单
    GSP -> SCM: 生成逆向入库申请单

    SCM ->  SCM:匹配入库申请单
    alt SCM入库申请单匹配失败
        loop
            SCM -> GSP: 通知实收商品明细
            GSP -> GSP: 确认退货商品
            GSP -> SCM: 更新入库申请单商品
        end

    else SCM入库申请单匹配成功
        SCM -> GSP: 通知GSP已经检测
        GSP ->  GSP: 处理单已检测(已检测)
        alt 检测失败
            alt 折旧入库
                GSP ->  GSP: 保存处理单的报价信息
                GSP --> 订单中心: 通知订单中心处理单报价信息
                订单中心 --> 订单中心: 生成受理单的报价单

                alt 网点收款
                    GSP ->  GSP: 更新处理单支付信息
                    GSP -> 订单中心: 通知订单中心处理单收款信息
                    订单中心 -> 订单中心: 更新受理单报价单信息
                else 商城收款
                    用户 -> 订单中心: 支付受理单的报价单
                    订单中心 -> 订单中心: 更新受理单的报价单信息
                    订单中心 -> GSP: 通知GSP受理单已收款
                    GSP ->  GSP: 更新处理单支付信息
                end
                GSP --> 订单中心: 通知订单中心处理单已收货\n 1.收货的商品信息
                订单中心 -> 订单中心: 生成发货单
                订单中心 -> SCM: 订单中心推送发货单给SCM
                订单中心 -> 订单中心: 完成受理单
                订单中心 -> GSP: 通知换货受理单已完成
                GSP ->  GSP: 完成处理单(已完成)
            else 放弃换货
                group 用户放弃换货
                    订单中心 -> 订单中心: 取消受理单的报价单
                    订单中心 -> 订单中心: 退回受理单
                    订单中心 -> GSP: 通知GSP退回处理单
                end group
                GSP ->  GSP: 将处理单退回(已退回)
                GSP --> 订单中心: 通知订单中心退回处理单\n 1.通知处理单已退回\n 2.告知退回处理单的取机信息
            end
        end
        GSP --> 订单中心: 通知订单中心处理单已收货\n 1.收货的商品信息
        订单中心 -> 订单中心: 生成发货单
        订单中心 -> SCM: 订单中心推送发货单给SCM
        订单中心 -> 订单中心: 完成受理单
        订单中心 -> GSP: 通知换货受理单已完成
        GSP ->  GSP: 完成处理单(已完成)
    end
end

@endnuml