@startuml

header
少发 且用户要求退款场景
endheader

actor 用户

用户 -> 订单中心: 创建物流退款受理单
订单中心 -> GSP: 通知GSP\n 1.受理单核心信息\n 2.受理单 Item\n 3.受理单地址
GSP -> GSP:创建处理单(已提交)

GSP -> GSP:审核处理单(已审核/已取消)
alt 审核取消
    GSP --> 订单中心: 通知订单中心取消受理单
    订单中心 --> 订单中心: 取消受理单
else 审核通过
    GSP --> 订单中心: 通知订单中心审核通过受理单
    GSP -> GSP: 物流确认(物流已确认)
    alt 需要取件回来
        GSP -> GSP: 预约取件时间
        GSP -> GSP: 上门取件
        GSP -> SCM: 生成逆向入库申请单
        GSP --> 订单中心: 通知订单中心处理单取回的商品信息
    end
    GSP -> GSP: 客服处理(处理中)
    GSP --> 订单中心: 通知订单中心退款
    订单中心 -> 订单中心: 生成退款单
    GSP -> 订单中心: 审核退款单
    GSP -> 订单中心: 执行退款
    订单中心 -> 订单中心: 完成受理单
    订单中心 -> GSP: 通知物流退款受理单已完成
    GSP ->  GSP: 完成处理单(已完成)
end

@endnuml