@startuml

actor 用户

用户 -> 订单中心: 创建退货受理单
订单中心 -> GSP: 通知GSP\n 1.受理单核心信息\n 2.受理单 Item\n 3.受理单地址
GSP -> GSP:创建处理单(已提交)

GSP -> GSP:审核处理单(已审核/已取消)
alt 审核取消
    GSP --> 订单中心: 通知订单中心取消受理单
    订单中心 --> 订单中心: 取消受理单
else 审核通过
    GSP --> 订单中心: 通知订单中心审核通过受理单

    GSP ->  GSP:检测处理单(已检测)
    alt 处理单检测不通过
        GSP ->  GSP:将处理单退回(已退回)
        GSP --> 订单中心: 通知订单中心退回处理单\n 1.通知处理单已退回\n 2.告知退回处理单的取机信息
        订单中心 -> 订单中心: 退回受理单
    else 处理单检测通过
        group 处理单入库
            GSP ->  GSP: 将处理单置为已收货(已收货)
            GSP -> SCM: 生成逆向入库申请单
        end
        GSP --> 订单中心: 通知订单中心处理单已收货
        订单中心 -> 订单中心: 生成退款单
        GSP -> 订单中心: 审核退款单
        GSP -> 订单中心: 执行退款
        订单中心 -> 订单中心: 完成受理单
        订单中心 -> GSP: 通知退货受理单已完成
        GSP ->  GSP: 完成处理单(已完成)
    end
end

@endnuml