@startuml

|用户|
|官网|
|客服|
|订单中心|

|用户|
start
:申请售后;
if(手机来源)then(官网购买)
    if(申请渠道)then(官网申请)
        |官网|
        :自助创建;
    else(客服申请)
        |客服|
        :客服创建;
    endif
else(第三方渠道购买)
|客服|
:客服创建;
endif
|订单中心|
:创建受理单;
end

@enduml