
@startuml

|物流人员|
start
:申请物流还款;
|订单|
:创建物流还款单#1;
|售后|
:审核RMA单;

if(是否通过审核)then(否)
    :取消RMA单#2;
    stop
endif

|售后|
:更新RMA为已审核#3;

|订单|
:创建退款单;
|售后|
:发起退款;
|订单|
:更新退款单状态;

:更新物流还款单状态#4;

@endnuml

#1 通知售后 创建RMA
#2 通知订单 取消物流还款单
#3 通知订单 通过物流还款单
#4 通知售后 完成RMA