
@startuml

|支付|
    |WMS|
|订单|
|用户|
|售后|
|用户|
start
:申请换货;
|支付|
|订单|
:创建换货单#1;
|售后|
:审核RMA单;

|售后|
if(是否通过审核)then(否)
    |售后|
    :取消RMA单#2;
    stop
endif

|售后|
:通过RMA#3;

|用户|
:寄送商品;

|售后|
:确认收到RMA的商品#4;



|售后|
if(判断需要是否终止售后)then(是)
     |售后|
    :取消RMA#5;
    stop
endif


|售后|
if(是否需要支付售后费用)then(是)
    |售后|
    :确认换货单的报价#6;
    |用户|
    :支付售后费用;
    if(支付方式)then(在线支付)
        |支付|
        :售后单的支付通知;
    endif
     |订单|
     :更新换货单为已支付#7;
endif

|订单|
if(判断服务区) then (欧美，印度)
    |订单|
    :生成发货单;
    :推送发货单;
    |WMS|
    :发货单已出库;
    :更新换货单包裹为出库;
    :完成换货单#11;
    stop;
else (国内)
    |售后|
    :更新RMA的商品信息#9;
    :填写寄回物流并完成换货单#10;
    stop;
endif

@endnuml

#1  通知售后 创建RMA
#2  通知订单 取消换货单
#3  通知订单 通过换货单
#4  通知订单 确认换货单的商品
#5  通知订单 取消换货单并更新取消物流;
#6  通知订单 更新换货单的应付金额
#7  通知售后 更新RMA为已支付
#9  通知订单 更新换货单的商品信息
#10 通知订单 完成换货单并填写寄回物流
@11 通知售后 完成RMA并填写寄回物流