
@startuml
|售后|
|物流人员|
start
:申请补发;
|订单|
:创建补发单#1;

|售后|
:审核补发单;

if(是否通过审核)then(否)
    :取消RMA单#2;
    stop
endif

|售后|
:更新RMA为已审核#3;

|物流人员|
if(确认是否可补发) then(否)
    |售后|
    :取消RMA#4;
    stop
endif


|售后|
:补发单已确认;
|订单|
:创建补发发货单;
:推送补发发货单;
|WMS|
:包裹出库;
|订单|
:确认补发包裹已出库;
:更新补发单状态#6;

stop;
@endnuml

#1 通知售后 创建RMA
#2 通知订单 取消补发单
#3 通知订单 通过补发单
#4 通知订单 取消补发单
#5 通知订单 物流通过，可以补发
#6 通知售后 完成RMA并更新补发物流;
