@startuml
|支付|
|用户|
start
:申请维修;
|支付|
|订单|
:创建维修单#1;
|售后|
:审核RMA单;
if(是否通过审核)then(否)
    |售后|
    :取消RMA单#2;
    stop
endif

|售后|
:RMA变更为通过#3;

|用户|
:寄送商品;
|售后|
::确认RMA的商品已收到#4;


|售后|
if(判断需要是否终止售后)then(是)
    |售后|
    :取消RMA#5;
    stop
endif

|售后|
if(是否需要支付售后费用)then(是)
    |售后|
    :确认换货单的报价#6;
    |用户|
    :支付售后费用;
    if(支付方式)then(在线支付)
        |支付|
        :售后单的支付通知;
    endif
        |订单|
        :更新换货单为已支付#7;
endif

|售后|
:维修商品#9;

|售后|
:完成RMA#10;
stop
@endnuml

#1 通知售后 创建RMA
#2 通知订单 取消维修单
#3 通知订单 通过维修单
#4 通知订单 确认维修单的商品
#5 通知订单 取消维修单并带上取消物流
#6 通知订单 更新维修单的应付金额
#7 通知订单 更新RMA状态为已支付
#9 通知订单 更新维修单的商品已处理
#10 通知售后 完成RMA并更新寄回物流
