@startuml

|用户|
start
:申请退货;
|订单|
:创建退货单#1;
|售后|
:审核RMA单;

if(是否通过审核)then(否)
    :取消RMA单#2;
    stop
endif

|售后|
:更新RMA为已审核#3;

|用户|
:寄送商品;

|售后|
:确认RMA的商品#4;

|售后|
if(判断需要是否终止售后)then(是)
     |售后|
    :取消RMA#5;
    stop
endif

|售后|
:确认已处理#6;

|订单|
:创建退款单;

|售后|
:发起退款;

|订单|
:更新退款单状态;
:更新退货单状态#7;

@endnuml

#1  通知售后 创建RMA
#2  通知订单 取消退货单
#3  通知订单 通过退货单
#4  通知订单 确认退货单的商品
#5  通知订单 取消退货单并更新取消物流;
#7 通知订单 售后已处理
#6 通知售后 完成RMA