@startuml
package 国内 {
    package OPPO机房 {
        frame "ERP" {
            ["交易记录"]
            ["基础数据"]
        }
        database "ERP-Oracle" {
            [op_trans_headers_iface_s]
            [op_trans_lines_iface_s]
            [op_purchase_order_header]
        }
    }
    package 广州机房 {
        frame "OA" {
            ["OA部门领料"]

        }

        frame "Service-Dispatcher" {
        ["同步ERP表数据到WMS(<font color=red>Schedule</font>)"]
        ["消费MQ同步ERP中间表数据到ERP"]
        ["包装OA部门领料数据"]
        }

        frame "WMS_CN" {
            ["通用出库"]
            ["扫描WMS-ERP中间表发送MQ"]
            ["同步国内ERP基础数据"]
        }

        database "WMS-MySql-CN" {
            [wms_erp_header]
            [wms_erp_lines]
        }
    }
}

package 海外{
    cloud AWS机房 {
        frame "WMS_Global" {
            ["海外通用出库"]
            ["扫描海外WMS-ERP中间表发送MQ"]
            ["同步海外ERP基础数据"]
        }

        database "WMS-MySql-Global" {
            [wms_erp_headers]
            [wms_erp_line]
        }
    }
}



["OA部门领料"]-->["包装OA部门领料数据"]:CN

["包装OA部门领料数据"]--> ["通用出库"]:CN

["通用出库"] --> [wms_erp_header]
["通用出库"] --> [wms_erp_lines]

["OA部门领料"]-->["包装OA部门领料数据"]:Global

["包装OA部门领料数据"]--> ["海外通用出库"]:Global

["海外通用出库"] -->[wms_erp_headers]
["海外通用出库"] -->[wms_erp_line]

["扫描WMS-ERP中间表发送MQ"] -> ["消费MQ同步ERP中间表数据到ERP"]:MQ
["消费MQ同步ERP中间表数据到ERP"] ->[op_trans_headers_iface_s]
["消费MQ同步ERP中间表数据到ERP"] ->[op_trans_lines_iface_s]

["扫描海外WMS-ERP中间表发送MQ"]-> ["消费MQ同步ERP中间表数据到ERP"]:MQ


["同步ERP表数据到WMS(<font color=red>Schedule</font>)"] --> ["同步国内ERP基础数据"]:MQ
["同步ERP表数据到WMS(<font color=red>Schedule</font>)"] --> ["同步海外ERP基础数据"]:MQ


@enduml