@startuml
'国内流程
start
: 订单重复性校验;
: 订单属性校验;
:为订单填充其他属性;
:存储订单主数据;
:存储订单地址数据;
:存储订单发票信息;
:存储订单商品数据;
if (订单有效且包含保险商品) then (yes)
  :通知admin系统保险信息;
else (no)
endif
if (是否纯虚拟订单或仅收款订单) then (yes)
    :添加发运单;
    :通知ERP;
else (no)
endif
end
@enduml