@startuml

enum RMA单据类型{
    10: Return
    20: Replacement
    30: Repair
}
enum 服务类型{
     10:仓库
     20:网点
}
enum 寄回方式{
    10:自行寄回
    20:上门取件
    30:带至网点
    40:送至网点
}

enum 寄回给用户方式{
    10:自行寄回
    20:上门取件
}

enum RMA来源{
    10: Customer
    20: Call Center
    30: Reverse Logitic
    40: Service Center
}

enum 维修类别 {
    保内：InWarranty
    保外：OutOfWarranty
}

enum 高低价值{
   10:低价值
   20:高价值
}

enum 退款单类型{
    10:线上退款单
    20:线下退款单
}

enum 退款单来源类型{
    0:默认退款单
    10:RMA售后退款单
    20:LMA售中退款单
    30:无实物
}

class RMA主单核心信息{
    RMA单号
    服务区域
    RMA来源
    RMA单据类型
    用户id
    工单号
    订单号
    订单购买渠道
    订单购买时间
    状态
    备注
    RMA服务类型
    网点仓库编号
    网点仓库电话号码
    网点仓库逆向单据ID
    申请原因
    申请原因描述
    取消时间
    取消原因
    取消原因类型
    发票号
    创建时间
    审核时间
    完成时间
    是否特批
    拒绝原因
    地址是否确认
}

class RMA网点处理信息{
    RMA单号
    检测备注
    处理方式
    维修详情
    维修级别
    软件版本
    网点受理时间
    维修类别
    等待原因
    等待类型
    RMA派单原因
    故障分类10：软件 20：硬件
    详细的故障描述
    新软件版本
}

class RMA物流信息{
    RMA单号
    客户发货时间
    网点收货时间
    网点寄出时间
    客户是否收货
    客户收货时间
    寄回方式,
    寄回物流公司
    寄回物流单号
    寄回给用户方式
    寄回给用户物流公司
    寄回给用户物流单号
    运费
}

class RMA支付信息{
    RMA单号
    实收金额
    折旧金额
    退款金额
    支付状态
    支付方式
    人工费
}

class RMA附件信息{
    RMA单号
    上传人
    上传附件链接
}

class RMA商品{
    主键
    RMA主键
    父id
    原imei号1
    原imei号2
    新imei号1
    新imei号2
    商品编码
    商品名称
    订单数量
    提交数量
    原价金额
    折扣金额
    申请原因
    检测失败数量
    检测通过数量
    商品生产日期
    是否是实物
    商品英文名称
    商品类型英文名
    保修开始时间
}

class RMA地址{
    主键
    RMA主键
    类型
    用户id
    用户名称
    收货人名称
    联系电话
    email
    邮编
    国家
    国家名称
    省
    省名称
    市
    市名称
    区
    区名称
    街
    街名称
    详细地址
    收货人FirstName
    收货人LastName
    用户税号
}

class RMA坏料备件 {
    来源id主键
    维修类型
    sku编号
    领退料价格
    状态
    申请币种
    网点给用户报价
    服务商给用户报价币种
    服务商
    网点编号
    中文名称
    英文名称
    SKU机型
    SKU类型 主板、耗材等
    SKU高低价值
    备件当前所在仓库编码
    退料申请单id
    退料申请单id2
    创建时间
    创建人
    更新时间
    更新人
    最小包装数量
    RMA完成时间
    该SKU税费
    海关编码
    sku税率
}

class RMA好料备件{
    来源id主键
    RMA维修检测坏料表id
    维修类别
    sku编号
    领退料价格
    状态
    申请币种
    网点给用户报价
    服务商
    网点编号
    中文名称
    英文名称
    SKU机型，所个用逗号分隔
    SKU类型 主板、耗材等
    SKU高低价值
    备件当前所在仓库编码
    退料申请单id
    退料申请单id2
    创建时间
    创建人
    更新时间
    更新人
    最小包装数量
    RMA完成时间
    海关编码
    sku税率
}

class RMA退款单{
    退款单号
    创建时间
    创建人
    币种
    国家
    备注
    更新时间
    更新人
    订单金额
    订单号
    支付人
    支付时间
    paypal帐号
    产品类型描述
    退款金额
    退款单状态
    退款类型
    退款时间
    是否自动创建
    标识位，第一位：是否假退款
    是否虚拟退款
    来源主键
    退款单来源类型
    退款单类型
}
RMA主单核心信息-left..> RMA地址:dependent "1..*"
RMA主单核心信息-right..> RMA商品:dependent "1..*"
RMA主单核心信息-up..> RMA网点处理信息:dependent "1..1"

RMA主单核心信息-up..> RMA物流信息:dependent "1..*"
RMA主单核心信息-up..> RMA附件信息:dependent "1..*"

RMA主单核心信息-down..>RMA退款单:dependent "1..*"
RMA主单核心信息-down..>RMA坏料备件:dependent "1..*"
RMA主单核心信息-down..>RMA好料备件:dependent "1..*"
RMA主单核心信息-down..> RMA支付信息:dependent "1..1"
@enduml