@startuml
left to right direction
:wms定时任务:
:订单中心:
:第三方仓库:
:aftership:
:仓库作业员:

(新增发货单)
(取消发货单)
(发货单实存占用)
(推送发货单到第三方仓库)
(发货单出库)
(更新发货单路由信息)
(获取发货单路由信息)
(逆向收货)
(发票生成)
(购物清单生成)

:订单中心: --> (新增发货单)
:订单中心: --> (取消发货单)
:wms定时任务: --> (发货单实存占用)
:wms定时任务: --> (推送发货单到第三方仓库)
:第三方仓库: --> (发货单出库)
:wms定时任务: --> (推送运单信息到aftership)
:aftership: --> (更新发货单路由信息)
:订单中心: --> (获取发货单路由信息)
:第三方仓库: --> (逆向收货)
:wms定时任务: --> (逆向入库)
:仓库作业员: --> (发票生成)
:仓库作业员: --> (购物清单生成)

@enduml