@startuml
left to right direction

rectangle 订单中心  {
(发货单推送wms)
(取消发货单)
(订单开具电子发票)
(发货单物流路由查询)
(发货单变为已分配)
(发货单变为已出库)
(发货单变为已签收)
(发货单变为已拒收)
(订单信息查询)
(保存订单税率)
}

rectangle wms{
(接收发货单)
(发货单取消)
(发货单实存占用)
(推送发货单到第三方仓库)
(发货单出库)
(获取发货单路由信息)
(物流路由查询)
(逆向收货)
(逆向入库)
(电子发票生成)
(计算订单税率)
}
(发货单推送wms) --> (接收发货单)
(取消发货单) --> (发货单取消)
(发货单实存占用) ---> (发货单变为已分配)
(发货单出库) ---> (发货单变为已出库)
(获取发货单路由信息) ---> (发货单变为已签收)
(获取发货单路由信息) ---> (发货单变为已拒收)
(订单开具电子发票) ---> (电子发票生成)
(电子发票生成) ---> (订单信息查询)
(保存订单税率) ---> (计算订单税率)
(计算订单税率) ---> (订单信息查询)
(发货单物流路由查询)--->(物流路由查询)
@enduml