@startuml
actor 用户
用户 -> 商城: 换货售后申请 \n 1、RMA核心信息 \n 2、RMA地址 \n 3、RMA商品明细
商城 -> GSP:推送售后申请到GSP
GSP->GSP:校验RMA申请参数 \n 1、订单号必填 \n 2、RMA地址必填 \n 3、RMA商品明细不为空
actor 呼叫中心客服
GSP->SCM:根据订单号查询订单详情
SCM-->GSP:返回订单详情
GSP->GSP:校验订单信息 \n 1、订单存在SCM \n 2、订单非大订单类型 \n 3、订单状态是已发货
GSP->GSP:计算当前订单对应的SKU的可换数量
alt SKU申请售后数量大于可换数量
    GSP->GSP:提示可换数量不足异常
else SKU申请售后数量小于或者等于可换数量
    GSP->GSP:保存RMA申请单
end
呼叫中心客服->GSP:审核RMA信息操作
alt 取消
    GSP->GSP:更新RMA为已取消
else 审核 \n 1、编辑完善RMA申请信息 \n 2、选择仓库,派单RMA到仓库
    GSP->GSP:更新RMA待检测
    loop
        alt RMA状态为待检测或者待客服处理
            GSP->SCM:通知逆向入库
            SCM->SCM:逆向匹配
            alt 正常逆向入库
                SCM->GSP:通知RMA变更为正常入库
            else 非正常入库
                SCM->GSP:通知RMA匹配失败的结果
                GSP->SCM:通知最新的逆向信息(SKU)
            end
        end
    end
    alt 完结RMA操作
         GSP->GSP:RMA状态变成已完成
    else RMA创建换货订单操作
         GSP->KM:RMA创建换货订单操作
         alt 需要支付
             GSP->GSP:RMA状态变成等待付款
             alt 支付完成
                 GSP->GSP:RMA状态变成已完成状态
                 GSP->SCM:通知逆向入库
             else 拒绝支付
                 GSP->GSP:RMA状态变成退货拒收状态
             end
         else 不需要支付
            GSP->GSP:RMA状态变成已完成状态
         end
    end
end
@enduml