@startuml

title 相关接口：/factoryDelivery/crawlFactoryDeliveryImeiFromOppo                            \n/factoryDelivery/passCustomsForOverseaFactoryDelivery

actor 关务 as somebody

WMS -> OPPO:根据DeliveryRequestNo交货申请编号
activate WMS
OPPO -> WMS:返回该交货申请编号的所有sku明细信息
note right
如果sku有imei，会附带交货单号DeliveryId
end note
WMS -> WMS:校验返回的数据和FactoryDeliverySku的数据是否一致

deactivate WMS


WMS -> OPPO:根据返回的交货单号DeliveryId获取对应的IMEI信息
activate WMS
WMS -> WMS:保存返回的imei到FactoryDeliveryImei
alt 返回的imei在ImeiCenter表不存在
WMS->WMS:插入imeiCenter表
end
deactivate WMS

WMS -> WMS:更新FactoryDelivery状态为已发货或待清关，\n回写FactoryDelivery相关信息:收获方、收货地点、CusPoNo等
note right
海外销售为清关，
海外备货、国内销售&备货为已发货
end note
alt 工厂发货单为<font color=red>销售</font>类型
   WMS -> WMS:生成入库单PutawayHeader、入库单明细PutawayLine、PutawayImei
   WMS -> ERP:记录ERP
   alt 国内的工厂发货单(B2B订单)
        WMS -> WMS:插入SalesOrderImei表
        activate WMS
        WMS -> WMS:更新SalesOrder为已出库、未签收
        WMS -> WMS:更新ImeiCenter的此批记录state= 3已出库
        WMS -> ERP:抛erp(<font color=red>未更新库存</font>)
        WMS -> OPSS:通知出库
        deactivate WMS
   end
end
==海外<font color=red>销售</font>类型工厂发货单==
somebody -> WMS:填写清关时间，操作清关
WMS -> WMS:插入SalesOrderImei表
activate WMS
WMS -> WMS:更新ImeiCenter的此批记录state= 3已出库
WMS -> ERP:抛erp(<font color=red>未更新库存</font>)
WMS -> OPSS:通知出库
WMS -> WMS:更新FactoryDelivery的state状态清关为已发货
deactivate somebody

legend center
1.销售类型的工厂发货单来源Opss，在wms中salsOrder表B2B类型的记录关联
2.备货类型的工厂发货单来源收货通知单，在wms中ReceiptHeader表关联
end legend
@enduml