@startuml
hide members

Object as_applymateriel{
    applymaterielid VARCHAR(20) PRIMARY KEY NOT NULL,
    materielcode VARCHAR(40),
    materieldescr VARCHAR(200),
    materielname VARCHAR(100),
    qualitydepot VARCHAR(20),
    quantity INT(11),
    applysheetid VARCHAR(20),
    imeibarcode VARCHAR(40)
}
Object as_applysheet{
    applysheetid VARCHAR(20) PRIMARY KEY NOT NULL,
    applytype TINYINT(4),
    createtime DATETIME,
    createuser VARCHAR(40),
    modifytime DATETIME,
    modifyuser VARCHAR(40),
    servicenodecode VARCHAR(20),
    status TINYINT(4),
    wmsLinkedId VARCHAR(80),
    treatsheetid VARCHAR(20)
}
Object as_log{
    logid VARCHAR(40) PRIMARY KEY NOT NULL,
    content VARCHAR(6000),
    createtime DATETIME,
    createuser VARCHAR(40),
    logtype SMALLINT(6),
    sourceid VARCHAR(80)
}
Object as_lostimei{
    lostimeiid VARCHAR(20) PRIMARY KEY NOT NULL,
    bindemail VARCHAR(600),
    bindtel VARCHAR(300),
    buychannel TINYINT(4),
    channelaccount VARCHAR(300),
    contactemail VARCHAR(600),
    contacttel VARCHAR(300),
    contactuser VARCHAR(120),
    createtime DATETIME,
    createuser VARCHAR(40),
    goodscode VARCHAR(40),
    goodsname VARCHAR(300),
    imei VARCHAR(30),
    losttime DATETIME,
    memo VARCHAR(600),
    modifytime DATETIME,
    modifyuser VARCHAR(40),
    order_flow VARCHAR(40),
    receiver VARCHAR(300),
    receivertel VARCHAR(300),
    reporttime DATETIME,
    retrieveflag TINYINT(4),
    status TINYINT(4)
}
Object as_servicenode{
    servicenodeid VARCHAR(20) PRIMARY KEY NOT NULL,
    addr_city VARCHAR(60),
    addr_cityname VARCHAR(60),
    addr_detail VARCHAR(3000),
    addr_distr VARCHAR(60),
    addr_distrname VARCHAR(60),
    addr_prov VARCHAR(60),
    addr_provname VARCHAR(60),
    addr_street VARCHAR(60),
    addr_streetname VARCHAR(60),
    companyname VARCHAR(300),
    createtime DATETIME,
    mapshow TINYINT(4),
    modifytime DATETIME,
    opentime VARCHAR(60),
    parentid VARCHAR(20),
    partner INT(11),
    phonenumber VARCHAR(60),
    servicenodecode VARCHAR(20),
    servicenodename VARCHAR(300),
    status TINYINT(4),
    warehouse_code VARCHAR(40),
    workingdays VARCHAR(60),
    linkedemail VARCHAR(1000),
    descr VARCHAR(300),
    country VARCHAR(40) COMMENT '国家',
    servicenodetype INT(11) COMMENT '网点类型',
    accept_rma_type SMALLINT(6) COMMENT '可受理的RMA单类型',
    accept_country VARCHAR(2000) COMMENT '可受理的国家',
    not_accept_product VARCHAR(3000) COMMENT '不可受理的产品',
    website_url VARCHAR(300) COMMENT '网点网址',
    send_notify_email TINYINT(4) DEFAULT '0' COMMENT '是否发送通知邮件，1：发送  0：不发送',
    business_type TINYINT(4) COMMENT '业务类型 10:借用 20：买断',
    credit_amount BIGINT(20) COMMENT '信用额度',
    level TINYINT(4) COMMENT '网点级别 1:一级网点 2:二级网点',
    labour_fee INT(11) COMMENT '劳务(人工手工)费',
    servicenode_account VARCHAR(128) COMMENT '网点账户号码',
    servicenode_account_name VARCHAR(128) COMMENT '网点账户名称',
    gstin VARCHAR(128) COMMENT '网点税号',
    pan_code VARCHAR(128) COMMENT '网点公司识别号，政府唯一注册',
    post_code VARCHAR(60) COMMENT '网点邮编',
    ifsc_code VARCHAR(300),
    cin VARCHAR(300) COMMENT '公司身份证号',
    contact VARCHAR(300) COMMENT '联系人'
}
Object as_treatinvoice{
    invoiceid VARCHAR(20) PRIMARY KEY NOT NULL,
    checkitemcode VARCHAR(60),
    checkoutprice INT(11),
    createtime DATETIME,
    createuser VARCHAR(40),
    servicenodecode VARCHAR(20),
    status TINYINT(4),
    treatsheetid VARCHAR(20),
    paymenttype TINYINT(4)
}
Object as_treatsheet{
    treatsheetid VARCHAR(20) PRIMARY KEY NOT NULL,
    attachment VARCHAR(600),
    attitude TINYINT(4),
    cancelreason VARCHAR(600),
    customerid VARCHAR(80),
    reportertel VARCHAR(120) COMMENT '报修人电话号码',
    reporter VARCHAR(180) COMMENT '报修人姓名',
    discountprice INT(11),
    engineer VARCHAR(120),
    handlememo VARCHAR(600),
    handletime DATETIME,
    handletype TINYINT(4),
    imeinew VARCHAR(30),
    imei_no VARCHAR(30),
    initialmemo VARCHAR(600),
    inspectresult TINYINT(4),
    malfunctiondescr VARCHAR(600),
    order_flow VARCHAR(40),
    pickupmemo VARCHAR(600),
    pickuptime DATETIME,
    pickuper VARCHAR(180),
    receiptno VARCHAR(90),
    receivetime DATETIME,
    receiveuser VARCHAR(120),
    recheckTime DATETIME,
    reservetime DATETIME,
    sender VARCHAR(180),
    sendertel VARCHAR(120),
    servicenodecode VARCHAR(20),
    softwareversion VARCHAR(120),
    sourceid VARCHAR(80),
    sourcetype TINYINT(4),
    status TINYINT(4),
    surfacedescr VARCHAR(600),
    totalprice INT(11),
    type TINYINT(4),
    accepttime DATETIME,
    delayreasona SMALLINT(6),
    delayreasonb SMALLINT(6),
    emailflag TINYINT(4) DEFAULT '0',
    firstchecktime DATETIME,
    handlesolution VARCHAR(180),
    modifytime DATETIME,
    modifyuser VARCHAR(40),
    servicecode VARCHAR(40),
    createuser VARCHAR(40),
    createtime DATETIME,
    isthirdparty TINYINT(4) DEFAULT '0',
    repairlevel TINYINT(4),
    settlementprice INT(11),
    applysheetstatus TINYINT(4),
    expresscompany VARCHAR(200) COMMENT '物流公司名称',
    expresscompany_in VARCHAR(200) COMMENT '商品邮寄给网点物流单号',
    expressno VARCHAR(80) COMMENT '运单号',
    expressno_in VARCHAR(80) COMMENT '商品邮寄给网点物流单号',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object as_treatsheetgood{
    tsgoodsid VARCHAR(20) PRIMARY KEY NOT NULL,
    createtime DATETIME,
    goodscode VARCHAR(40),
    imei_new VARCHAR(30),
    imei_old VARCHAR(30),
    modifytime DATETIME,
    order_flow VARCHAR(40),
    treatsheetid VARCHAR(20),
    insuranceids VARCHAR(600),
    malfunctions VARCHAR(600),
    repairs VARCHAR(600),
    imei_old2 VARCHAR(30),
    imei_new2 VARCHAR(30),
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object cs_appraise{
    appraiseid VARCHAR(20) PRIMARY KEY NOT NULL,
    baseparent VARCHAR(20),
    content VARCHAR(900),
    createtime DATETIME,
    createuser VARCHAR(40),
    directparent VARCHAR(20),
    level TINYINT(4),
    sourceid VARCHAR(80) NOT NULL,
    receiveuser VARCHAR(40),
    state TINYINT(4) DEFAULT '0'
}
Object cs_category{
    categoryid VARCHAR(12) PRIMARY KEY NOT NULL,
    parentid VARCHAR(12),
    orderindex SMALLINT(6),
    rightindex SMALLINT(6),
    title VARCHAR(60),
    level TINYINT(4),
    status SMALLINT(6),
    flags SMALLINT(6),
    storeid TINYINT(4),
    createtime DATETIME,
    modifytime DATETIME,
    icon_img VARCHAR(1000) COMMENT 'icon图片url'
}
Object cs_collectionrss{
    collectrssid VARCHAR(20) PRIMARY KEY NOT NULL,
    collecttime DATETIME,
    customerid VARCHAR(80),
    iscollect TINYINT(4),
    isrss TINYINT(4),
    isrssupdated TINYINT(4),
    rsstime DATETIME,
    sourceid VARCHAR(80) NOT NULL,
    storeid TINYINT(4)
}
Object cs_feedback{
    feedbackid VARCHAR(40) PRIMARY KEY NOT NULL,
    sourceid VARCHAR(80),
    rank TINYINT(4),
    reason TINYINT(4),
    memo VARCHAR(600),
    usertype INT(11),
    storeid TINYINT(4),
    createtime DATETIME,
    createuser VARCHAR(40),
    type SMALLINT(6)
}
Object cs_knowledge{
    knowledgeid VARCHAR(40) PRIMARY KEY NOT NULL,
    categoryid VARCHAR(12),
    orderindex INT(11),
    title VARCHAR(300),
    content TEXT,
    attachment VARCHAR(3000),
    keywords VARCHAR(300),
    memo VARCHAR(600),
    status SMALLINT(6),
    flags SMALLINT(6),
    storeid TINYINT(4),
    createtime DATETIME,
    modifytime DATETIME,
    activatetimeend DATETIME,
    activatetimestart DATETIME,
    publishtime DATETIME,
    type SMALLINT(6),
    visitedcount INT(11),
    createuser VARCHAR(255),
    modifyuser VARCHAR(255),
    reference VARCHAR(3000),
    prop1 VARCHAR(300),
    prop2 VARCHAR(300),
    firstpagetype INT(4) DEFAULT '0' COMMENT '首页控制类型 0:默认 1:通知',
    store_codes VARCHAR(2000) COMMENT '知识库文章关联的商城编码，用英文逗号分隔。关联所有则取值all',
    component_flag VARCHAR(600) COMMENT '组件flag,用英文逗号分隔。 10:Live Chat, 20:Demage & Repair'
}
Object cs_log{
    logid VARCHAR(40) PRIMARY KEY NOT NULL,
    sourceid VARCHAR(80),
    content VARCHAR(6000),
    logtype SMALLINT(6),
    createtime DATETIME,
    createuser VARCHAR(40)
}
Object cs_maintainconf{
    mtconfid VARCHAR(12) PRIMARY KEY NOT NULL,
    mtconfcode VARCHAR(30),
    content TEXT,
    modifytime DATETIME,
    modifyuser VARCHAR(40)
}
Object cs_msghistory{
    msghistoryid VARCHAR(20) PRIMARY KEY NOT NULL,
    billstype SMALLINT(6),
    createtime DATETIME,
    createuser VARCHAR(255),
    customerid VARCHAR(80),
    memo VARCHAR(600),
    msgcontent VARCHAR(6000),
    phonenumber VARCHAR(60),
    replycode VARCHAR(600),
    replydescr VARCHAR(600),
    replytime DATETIME,
    sendtime DATETIME,
    sourceid VARCHAR(80),
    status SMALLINT(6),
    tplcode VARCHAR(20)
}
Object cs_msgreplycode{
    msgreplycodeid VARCHAR(20) PRIMARY KEY NOT NULL,
    createtime DATETIME,
    createuser VARCHAR(255),
    msgtplid VARCHAR(20),
    replycode VARCHAR(600),
    replydescr VARCHAR(600)
}
Object cs_msgtemplate{
    msgtplid VARCHAR(20) PRIMARY KEY NOT NULL,
    billstype SMALLINT(6),
    createtime DATETIME,
    createuser VARCHAR(255),
    descr VARCHAR(600),
    modifytime DATETIME,
    modifyuser VARCHAR(255),
    status SMALLINT(6),
    tplcode VARCHAR(60),
    tplcontent VARCHAR(6000),
    tplname VARCHAR(60),
    type SMALLINT(6)
}
Object cs_msgtpldata{
    msgtpldataid VARCHAR(20) PRIMARY KEY NOT NULL,
    billstype SMALLINT(6),
    createtime DATETIME,
    createuser VARCHAR(255),
    datacode VARCHAR(600),
    dataname VARCHAR(60),
    datatype VARCHAR(200)
}
Object cs_notice_relation{
    relationid VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '通知关联表id',
    notificationid VARCHAR(20) COMMENT '通知主表id',
    receiveuser VARCHAR(80) COMMENT '接收者',
    createuser VARCHAR(80) COMMENT '创建者',
    createtime DATETIME COMMENT '创建时间',
    isread TINYINT(4) DEFAULT '0' COMMENT '是否已读'
}
Object cs_notification{
    notificationid VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '通知主表主键',
    sourceid VARCHAR(80) COMMENT '通知来源主键',
    title VARCHAR(500) COMMENT '通知标题',
    content VARCHAR(600) COMMENT '通知内容',
    type TINYINT(4) COMMENT '通知类型',
    createuser VARCHAR(80) COMMENT '创建者',
    createtime DATETIME COMMENT '创建时间',
    state TINYINT(4) DEFAULT '0' COMMENT '是否删除状态,默认是0表示未删除'
}
Object gs_common_notes{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    type SMALLINT(6) COMMENT '业务类型',
    source_id VARCHAR(80) COMMENT '关联业务主键',
    content VARCHAR(600) COMMENT '备注内容',
    create_user VARCHAR(80) COMMENT '创建人员',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(80) COMMENT '修改人员',
    modify_time DATETIME COMMENT '修改时间'
}
Object gs_email_content{
    email_content_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '发送内容id',
    source_title VARCHAR(300) COMMENT '发送主题',
    source_content TEXT,
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建用户'
}
Object gs_email_history{
    email_history_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '发送历史id',
    bills_type SMALLINT(6) COMMENT '业务类型',
    email_content_id VARCHAR(80) COMMENT '发送内容id',
    email_template_id VARCHAR(80) COMMENT '发送模板id',
    from_email VARCHAR(80) NOT NULL COMMENT '发送人',
    send_to_email VARCHAR(3000) COMMENT '收件人',
    source_id VARCHAR(80) COMMENT '来源主键id',
    source_status SMALLINT(6) COMMENT '来源状态',
    create_user VARCHAR(40) COMMENT '创建用户',
    create_time DATETIME COMMENT '创建时间',
    status SMALLINT(6) COMMENT '发送状态',
    send_time DATETIME COMMENT '发送时间',
    server_path_type SMALLINT(6),
    send_to_email_bcc VARCHAR(3000) COMMENT '私密收件人',
    send_to_email_cc VARCHAR(3000) COMMENT '抄送收件人',
    err_msg TEXT COMMENT '发送失败信息'
}
Object gs_email_rule{
    email_rule_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '发送规则id',
    country VARCHAR(255) COMMENT '国家',
    email_rule_name VARCHAR(255) COMMENT '规则名称',
    email_template_id VARCHAR(80) COMMENT '模板id',
    create_user VARCHAR(40) COMMENT '创建人',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(255) COMMENT '修改人',
    modify_time DATETIME COMMENT '修改时间',
    source_status INT(11) COMMENT '来源状态',
    source_type INT(11) COMMENT '来源类型',
    status INT(11) COMMENT '状态 10：激活 20：激活',
    send_to_email_ext VARCHAR(255)
}
Object gs_email_template{
    template_id INT(10) UNSIGNED PRIMARY KEY NOT NULL COMMENT '模版id' AUTO_INCREMENT,
    template_code VARCHAR(150) NOT NULL COMMENT '模版名称',
    template_subject VARCHAR(200) NOT NULL COMMENT '模版主题',
    template_text TEXT NOT NULL COMMENT '模板内容',
    template_styles TEXT COMMENT '模版样式',
    template_type INT(10) UNSIGNED COMMENT '模板类型',
    template_sender_name VARCHAR(200) COMMENT '发送人',
    template_sender_email VARCHAR(200) COMMENT '发送人邮箱',
    status INT(11) COMMENT '状态 10：激活 20：激活 30:删除',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '修改世间',
    modify_user VARCHAR(40) COMMENT '修改人'
}
Object gs_malfunct_code{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    code_type INT(11) COMMENT '编码类型(10:故障代码, 20:维修代码)',
    code VARCHAR(80) COMMENT '编号',
    type VARCHAR(20) COMMENT '分类类型'
}
Object gs_malfunct_lang{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    malfunct_code_id INT(11) NOT NULL COMMENT '故障-原因代码主键',
    language VARCHAR(40) COMMENT '语言',
    descr VARCHAR(600) COMMENT '描述',
    memo VARCHAR(600) COMMENT '备注',
    create_user VARCHAR(80) COMMENT '创建人员',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(80) COMMENT '修改人员',
    modify_time DATETIME COMMENT '修改时间',
    weight INT(11),
    status SMALLINT(6) COMMENT '状态'
}
Object gs_quotation_code{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    machine_type VARCHAR(20) COMMENT '机型',
    type VARCHAR(20) COMMENT '类型',
    goods_code VARCHAR(40) COMMENT '商品编码'
}
Object gs_quotation_lang{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    quotation_code_id INT(11) COMMENT '非保价项编码主键',
    descr VARCHAR(600) COMMENT '描述',
    language VARCHAR(40) COMMENT '语言',
    currency VARCHAR(40) COMMENT '币种',
    price INT(11) COMMENT '价格',
    compose VARCHAR(600) COMMENT '所属组件',
    memo VARCHAR(600) COMMENT '备注',
    create_user VARCHAR(80) COMMENT '创建人员',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(80) COMMENT '修改人员',
    modify_time DATETIME COMMENT '修改时间',
    weight INT(11),
    status SMALLINT(6) COMMENT '状态'
}
Object gs_rma_address{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    rma_sheet_id VARCHAR(40) COMMENT 'RMA主键',
    customer_id VARCHAR(80) COMMENT '用户id',
    customer_name VARCHAR(300) COMMENT '用户名称',
    receiver_name VARCHAR(300) COMMENT '收货人名称',
    receiver_first_name VARCHAR(60) COMMENT '收货人名称 firstname',
    receiver_last_name VARCHAR(60) COMMENT '收货人名称 lastname',
    gstin VARCHAR(128) COMMENT '用户税号',
    phone_number VARCHAR(60) COMMENT '联系电话',
    email VARCHAR(300) COMMENT 'email',
    post_code VARCHAR(60) COMMENT '邮编',
    country VARCHAR(40) COMMENT '国家',
    country_name VARCHAR(300) COMMENT '国家名称',
    addr_prov VARCHAR(40) COMMENT '省',
    addr_prov_name VARCHAR(300) COMMENT '省名称',
    addr_city VARCHAR(40) COMMENT '市',
    addr_city_name VARCHAR(300) COMMENT '市名称',
    addr_distr VARCHAR(40) COMMENT '区',
    addr_distr_name VARCHAR(300) COMMENT '区名称',
    addr_street VARCHAR(200) COMMENT '街',
    addr_street_name VARCHAR(600) COMMENT '街名称',
    addr_detail VARCHAR(900) COMMENT '详细地址',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object gs_rma_checkcode{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    rma_sheet_id VARCHAR(40) COMMENT 'RMA主键',
    type SMALLINT(6) COMMENT '类型',
    check_code VARCHAR(20) COMMENT '检测项编号(非保价项编号)',
    create_user VARCHAR(40) COMMENT '创建人员',
    create_time DATETIME COMMENT '创建时间',
    status INT(4) COMMENT '状态 10:待审核 20:已审核 30:已生成报表 40:已生成退料单',
    apply_sheet_id VARCHAR(40) COMMENT '备件申请单id',
    report_id VARCHAR(40) COMMENT '报表id'
}
Object gs_rma_goods{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    rma_sheet_id VARCHAR(40) COMMENT 'RMA主键',
    parent_id VARCHAR(40) COMMENT '父id',
    imei_old1 VARCHAR(40) COMMENT '原imei号1',
    imei_old2 VARCHAR(40) COMMENT '原imei号2',
    imei_new1 VARCHAR(40) COMMENT '新imei号1',
    imei_new2 VARCHAR(40) COMMENT '新imei号2',
    type VARCHAR(50) COMMENT '商品类型',
    goods_code VARCHAR(40) COMMENT '商品编码',
    goods_name VARCHAR(300) COMMENT '商品名称',
    production_date DATETIME COMMENT '生产日期',
    order_qty INT(11) COMMENT '订单数量',
    submit_qty INT(11) COMMENT '提交数量',
    check_pass_num INT(11) COMMENT '检测通过数量',
    check_failed_num INT(11) COMMENT '检测不通过数量',
    original_price INT(11) COMMENT '原价金额',
    discount_amount INT(11) COMMENT '折扣金额',
    apply_reason VARCHAR(600) COMMENT '申请原因',
    product_date DATETIME,
    is_material TINYINT(4),
    en_goods_name VARCHAR(300) COMMENT '商品英文名称',
    en_type VARCHAR(50) COMMENT '商品类型英文名',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    warranty_start_time DATETIME COMMENT '保修开始时间'
}
Object gs_rma_postcode{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    country VARCHAR(50),
    country_name VARCHAR(100),
    province VARCHAR(50),
    province_name VARCHAR(100),
    post_code VARCHAR(30)
}
Object gs_rma_sheet{
    rma_sheet_id VARCHAR(40) PRIMARY KEY NOT NULL COMMENT 'RMA单id',
    service_zone SMALLINT(6) COMMENT '服务区域',
    purchase_channel SMALLINT(6) DEFAULT '100' COMMENT '购买渠道 100：官网',
    customer_id VARCHAR(80) COMMENT '用户id',
    ticket_no VARCHAR(80) COMMENT '海外工单票号',
    source_id VARCHAR(80) COMMENT '来源id',
    new_orderno VARCHAR(80) COMMENT '新订单号',
    source_complete_time DATETIME COMMENT '来源单据完成时间',
    status SMALLINT(6) COMMENT '状态',
    customer_received SMALLINT(6) COMMENT '用户是否已收货',
    address_verified SMALLINT(6) DEFAULT '0' COMMENT '地址是否已确认',
    type SMALLINT(6) COMMENT '单据类型',
    service_type SMALLINT(6) COMMENT '服务类型',
    swap_create_type SMALLINT(6) COMMENT '换货单创建类型',
    swap_order_no VARCHAR(80) COMMENT '换货单号',
    house_sheet_id VARCHAR(80) COMMENT '仓库网点单据id',
    house_code VARCHAR(80) COMMENT '仓库网点编号',
    house_tel VARCHAR(40) COMMENT '仓库网点电话号码',
    return_method SMALLINT(11) COMMENT '寄回方式',
    purchase_time DATETIME COMMENT '购买时间',
    appoint_time DATETIME COMMENT '预约申请时间',
    currency VARCHAR(40),
    checkout_price INT(11) COMMENT '实收金额',
    labour_fee INT(11) COMMENT '劳务(人工手工)费',
    invoice_no VARCHAR(128) COMMENT '印度发票号',
    depreciate_price INT(11) COMMENT '折旧金额',
    refund_amount INT(11) COMMENT '退款金额',
    pay_status SMALLINT(6) COMMENT '支付状态',
    pay_type SMALLINT(6) COMMENT '支付方式',
    reason_descr VARCHAR(600) COMMENT '原因描述',
    create_user VARCHAR(80) COMMENT '创建人员',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(80) COMMENT '修改人员',
    modify_time DATETIME COMMENT '修改时间',
    carrier VARCHAR(80) COMMENT '物流公司',
    tracking_no VARCHAR(600),
    carriage_price INT(11) COMMENT '运费',
    cancel_reason VARCHAR(600) COMMENT '取消原因',
    reject_reason VARCHAR(600) COMMENT '拒绝原因',
    return_tracking_no VARCHAR(600),
    memo VARCHAR(600) COMMENT '备注',
    inspect_remark VARCHAR(600) COMMENT '检测备注',
    treatment_type SMALLINT(6) COMMENT '处理方式',
    repair_detail VARCHAR(600) COMMENT '维修详情',
    repairment_level SMALLINT(6) COMMENT '维修级别',
    software_version VARCHAR(300) COMMENT '软件版本',
    appoint_accepted_time DATETIME COMMENT '安排收货时间',
    customer_received_time DATETIME COMMENT '用户收货时间',
    customer_send_time DATETIME COMMENT '用户寄出时间',
    house_received_time DATETIME COMMENT '网点收货时间',
    house_send_time DATETIME COMMENT '网点寄出时间',
    return_tracking_carrier VARCHAR(255) COMMENT '客户寄回物流公司',
    treatment_type2 SMALLINT(6) COMMENT '处理方式二级字段',
    rma_reason SMALLINT(6) COMMENT 'RMA派单原因',
    pending_type SMALLINT(6) COMMENT 'RMA单等待状态类型',
    pending_reason VARCHAR(200) COMMENT 'RMA单等待原因',
    attachment VARCHAR(3000) COMMENT '附件地址',
    flags INT(11) DEFAULT '0' COMMENT '标识位，第一位：是否特批',
    rma_source SMALLINT(6) COMMENT 'RMA单来源',
    apply_reason VARCHAR(300),
    apply_reason_desc VARCHAR(2000) COMMENT '用户申请原因描述',
    attach_user VARCHAR(3000) COMMENT '用户上传附件',
    approve_time DATETIME,
    rsp_order VARCHAR(40) COMMENT '服务商RMA主键',
    cancel_time DATETIME COMMENT '取消时间',
    cancel_reason_type SMALLINT(6) COMMENT '取消原因类型',
    customer_id_type SMALLINT(6) COMMENT '用户id类型 10：userid 20:openid',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    complete_time DATETIME COMMENT 'RMA单据完成时间',
    version INT(11) DEFAULT '0' COMMENT '乐观锁版本字段',
    invoiceNo VARCHAR(255)
}
Object gs_spareparts_apply_goods{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键id' AUTO_INCREMENT,
    apply_sheet_id VARCHAR(40) COMMENT '申请单id',
    goods_code VARCHAR(40) COMMENT '商品编号',
    goods_name VARCHAR(200) COMMENT '商品名称',
    currency VARCHAR(20) COMMENT '币种',
    price INT(11) COMMENT '价格',
    count INT(11) COMMENT '数量',
    in_stock_count INT(11) COMMENT '网点已入库数量',
    return_count INT(11) COMMENT '网点已退数量',
    in_transit_count INT(11) COMMENT '总仓出库在途数量',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    apply_type TINYINT(4) COMMENT '审核类型 10：领料 20：退料 30：借转销 40：报废',
    source_id VARCHAR(40) COMMENT '来源SKU主键',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    version INT(11) DEFAULT '0' COMMENT '版本号',
    goods_en_name VARCHAR(300) COMMENT '备件英文名称',
    value INT(11) COMMENT 'SKU高低价值',
    machine_types VARCHAR(40) COMMENT 'SKU机型',
    type VARCHAR(40) COMMENT 'SKU类型',
    approved_count INT(11) COMMENT '已审核数量',
    min_pck_qty INT(11) COMMENT '最小打包数量',
    source_apply_sheet_id VARCHAR(40) COMMENT '来源领料申请主键id',
    consignment_sell_count INT(11) COMMENT '借转销数量'
}
Object gs_spareparts_applysheet{
    apply_sheet_id VARCHAR(40) PRIMARY KEY NOT NULL COMMENT '申请单id',
    apply_type TINYINT(4) COMMENT '申请类型 10:领料 20:退料',
    warehouse_code VARCHAR(50) COMMENT '仓库编号',
    warearea_code VARCHAR(50),
    in_warehouse_code VARCHAR(50) COMMENT '调入仓库编号',
    out_warehouse_code VARCHAR(50) COMMENT '调出仓库编号',
    is_borrow_switch TINYINT(4) COMMENT '是否借转销 0:否 1:是',
    status INT(11) COMMENT '申请单状态',
    total_amount INT(11) COMMENT '申请总数量',
    memo VARCHAR(600) COMMENT '备注',
    cancel_reason VARCHAR(600) COMMENT '取消原因',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    warehouse_name VARCHAR(255),
    original_can_used_amount BIGINT(20) COMMENT '原始保证金',
    business_type TINYINT(4) COMMENT '业务类型 0:无 10:借用 20：买断',
    service_node_code VARCHAR(20) COMMENT '网点编号',
    service_node_name VARCHAR(300) COMMENT '网点名称',
    in_warehouse_area_code VARCHAR(255) COMMENT '发货仓库库区编码',
    in_warehouse_area_name VARCHAR(255) COMMENT '发货仓库库区名称',
    in_warehouse_name VARCHAR(255) COMMENT '发货仓库名称',
    out_warehouse_area_code VARCHAR(255) COMMENT '收货仓库库区编码',
    out_warehouse_area_name VARCHAR(255) COMMENT '收货仓库库区名称',
    out_warehouse_name VARCHAR(255) COMMENT '收货仓库名称',
    return_type VARCHAR(40) COMMENT '退货类型 OK，RMA，DOA',
    currency VARCHAR(40) COMMENT '币种',
    stock_sheet_id VARCHAR(1000) COMMENT '发货单id',
    is_cancel_after_approve TINYINT(4) DEFAULT '0' COMMENT '是否审核之后取消'
}
Object gs_spareparts_sku_stockgoods{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键id' AUTO_INCREMENT,
    apply_sheet_id VARCHAR(1000) COMMENT '备件申请单id',
    stock_sheet_id VARCHAR(40) COMMENT '出入库单据id',
    goods_code VARCHAR(40) COMMENT '商品编号',
    goods_name VARCHAR(255) COMMENT '商品名称',
    box_code VARCHAR(255) COMMENT '箱号',
    count INT(11) COMMENT '申请数量',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    source_id VARCHAR(40),
    goods_en_name VARCHAR(300) COMMENT '备件英文名称',
    machine_types VARCHAR(40) COMMENT '机型',
    type VARCHAR(40) COMMENT 'SKU类型',
    value INT(11) COMMENT '高低价值 10 :低 20：高'
}
Object gs_spareparts_sku_stockimei{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键id' AUTO_INCREMENT,
    apply_sheet_id VARCHAR(1000) COMMENT '备件申请单id',
    box_code VARCHAR(40) COMMENT '箱号',
    goods_code VARCHAR(40) COMMENT '商品编号',
    imei VARCHAR(30) COMMENT 'imei编号',
    imei2 VARCHAR(30) COMMENT 'imei编号',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    source_id VARCHAR(40),
    status INT(11)
}
Object gs_spareparts_sku_stocksheet{
    stock_sheet_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '出入库单据id',
    apply_sheet_id VARCHAR(1000) COMMENT '备件申请单id',
    out_warehouse_code VARCHAR(40) COMMENT '出库仓库编号',
    out_warearea_code VARCHAR(40) COMMENT '出库仓库库区编号',
    in_warehouse_code VARCHAR(40) COMMENT '入库仓库编号',
    in_warearea_code VARCHAR(40) COMMENT '入库仓库库区编号',
    status INT(11) COMMENT '状态',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    in_warehouse_name VARCHAR(255) COMMENT '入库仓库名称',
    out_warehouse_name VARCHAR(255) COMMENT '出库仓库名称',
    apply_type TINYINT(4) COMMENT '申请类型',
    business_type TINYINT(4) COMMENT '网点备件业务模式 10：借用 20:买断',
    return_type VARCHAR(40) COMMENT '退料类型 OK，RMA，DOA',
    service_node_code VARCHAR(20) COMMENT '申请网点编号',
    service_node_name VARCHAR(300) COMMENT '申请网点名称',
    total_amount BIGINT(20) COMMENT '发货单总金额',
    in_warearea_name VARCHAR(255) COMMENT '入库仓库库区名称',
    out_warearea_name VARCHAR(255) COMMENT '出库仓库库区名称',
    is_borrow_switch TINYINT(4) COMMENT '是否借转销 0:否 1:是',
    currency VARCHAR(40) COMMENT '币种',
    receive_sequence VARCHAR(255) COMMENT '收货次数序号'
}
Object gs_thirdplat_goods{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    content VARCHAR(6000) COMMENT '第三方回传的商品内容',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    plat_type TINYINT(4) COMMENT '平台类型',
    source_id VARCHAR(40) COMMENT '来源主键',
    order_no VARCHAR(40) COMMENT '订单编号'
}
Object gs_warehouse_fund{
    warehouse_fund_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '仓库保证金额度id',
    warehouse_code VARCHAR(80) COMMENT '仓库编码',
    warehouse_name VARCHAR(255) COMMENT '仓库名称',
    total_present_amount BIGINT(20) COMMENT '总的赠送额度',
    total_cash_amount BIGINT(20) COMMENT '总的现金额度',
    total_pre_used_amount BIGINT(20) COMMENT '总的预占用额度',
    total_used_amount BIGINT(20) COMMENT '总的占用额度',
    version INT(11) COMMENT '版本',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    modify_time DATETIME COMMENT '修改时间',
    modify_user VARCHAR(40) COMMENT '修改人',
    currency VARCHAR(40)
}
Object gs_warehouse_fund_flow{
    warehouse_fund_flow_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '保证金流水id',
    warehouse_fund_id VARCHAR(80) COMMENT '保证金id',
    fund_flow_type SMALLINT(6) COMMENT '流水类型',
    is_borrow_switch TINYINT(4) COMMENT '是否借转销 0:否 1:是',
    source_id VARCHAR(80) COMMENT '来源id',
    pre_used_amount BIGINT(20) COMMENT '预占用金额',
    used_amount BIGINT(20) COMMENT '占用金额',
    total_cash_amount BIGINT(20) COMMENT '总的现金金额',
    total_present_amount BIGINT(20) COMMENT '总的赠送金额',
    total_pre_used_amount BIGINT(20) COMMENT '总的预占用金额',
    total_used_amount BIGINT(20) COMMENT '总的占用金额',
    update_amount BIGINT(20) COMMENT '变更金额',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    memo VARCHAR(600) COMMENT '备注',
    business_type TINYINT(4) COMMENT '业务类型 0:无 10:借用 20：买断',
    service_node_code VARCHAR(20) COMMENT '网点编号',
    service_node_name VARCHAR(300) COMMENT '网点名称'
}
Object t_address{
    id INT(7) UNSIGNED PRIMARY KEY NOT NULL COMMENT '地址Id' AUTO_INCREMENT,
    addr_id INT(20) COMMENT '用户中心地址主键',
    addr_no VARCHAR(30) COMMENT '地址编号',
    name VARCHAR(250) COMMENT '收货人姓名',
    phone VARCHAR(20) COMMENT '固定电话',
    mobile VARCHAR(20) COMMENT '移动电话',
    province_id VARCHAR(32) COMMENT '省ID',
    province VARCHAR(100) COMMENT '省',
    city_id VARCHAR(32) COMMENT '市ID',
    city VARCHAR(100) COMMENT '市',
    area_id VARCHAR(32) COMMENT '区ID',
    area VARCHAR(100) COMMENT '区',
    street_id VARCHAR(32) COMMENT '街道ID',
    street VARCHAR(500) COMMENT '街道地址',
    post_code VARCHAR(10) COMMENT '邮编',
    create_date DATETIME COMMENT '创建时间',
    update_date DATETIME COMMENT '修改时间',
    user_id VARCHAR(30),
    detail VARCHAR(200) COMMENT '地址详情',
    biz_no VARCHAR(32),
    biz_type VARCHAR(2)
}
Object t_biz_log{
    id INT(20) UNSIGNED PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    biz_no VARCHAR(30),
    order_flow VARCHAR(40) COMMENT '订单号',
    oper_id VARCHAR(15) COMMENT '操作人ID  ',
    oper_name VARCHAR(50) COMMENT '操作人名   ',
    oper_type SMALLINT(1) DEFAULT '1' COMMENT '操作类型',
    oper_ip VARCHAR(20) COMMENT '操作IP',
    biz_type SMALLINT(50) DEFAULT '1' COMMENT '业务类型',
    content VARCHAR(2000) COMMENT '日志内容',
    comments VARCHAR(200) COMMENT '评论',
    create_date DATETIME COMMENT '创建日期',
    status VARCHAR(2),
    oper_source VARCHAR(10) COMMENT '操作员类型,oper_type被占用了,只能用换个字段名了'
}
Object t_check_item{
    id INT(7) PRIMARY KEY NOT NULL COMMENT '检测项id' AUTO_INCREMENT,
    biz_no VARCHAR(30) NOT NULL COMMENT '业务单据号',
    biz_type VARCHAR(1) COMMENT '1.退货
            2.换货
            3.维修',
    description VARCHAR(300) COMMENT '检测项描述',
    code VARCHAR(10)
}
Object t_courier_state_map{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '物流与单据映射表Id' AUTO_INCREMENT,
    logistic_type VARCHAR(1) COMMENT '物流方式  1:EMS 2:顺丰  缺省值1',
    logistic_state VARCHAR(5) COMMENT '运单状态',
    bill_state VARCHAR(5) COMMENT '单据状态',
    bill_type VARCHAR(1) DEFAULT '1' COMMENT '单据类型 1:退货单 缺省值1',
    update_data DATETIME COMMENT '更新时间',
    create_data DATETIME COMMENT '创建时间'
}
Object t_depreciate_repair{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    repair_acceptance_no VARCHAR(30),
    repair_no VARCHAR(30),
    source_no VARCHAR(30),
    source_channel VARCHAR(1) COMMENT '1退货
            2 换货',
    state VARCHAR(1) NOT NULL COMMENT '1	有效待分配
2	待支付
3	已支付
4	待检测
5 	已检测
6	已完成
7	已取消

            ',
    pay_date DATETIME,
    pay_type VARCHAR(10) COMMENT '1 抵扣
            2 在线支付',
    total_fee INT(11),
    checker VARCHAR(20),
    check_date DATETIME,
    end_date DATETIME,
    create_user VARCHAR(20),
    create_date DATETIME,
    update_user VARCHAR(20),
    update_date DATETIME,
    cancel_user VARCHAR(30),
    cancel_date DATETIME,
    cancel_reason VARCHAR(200) COMMENT '换货单取消原因',
    remark VARCHAR(300),
    user_id VARCHAR(30),
    delay_fee INT(11),
    non_defend_fee INT(11),
    order_no VARCHAR(40)
}
Object t_depreciate_repair_acceptance{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    repair_acceptance_no VARCHAR(30),
    repair_no VARCHAR(30),
    source_no VARCHAR(30),
    source_channel VARCHAR(1) COMMENT '来源类型',
    state VARCHAR(1) NOT NULL,
    pay_type VARCHAR(10) COMMENT '支付类型',
    total_fee INT(11),
    checker VARCHAR(20),
    check_date DATETIME,
    end_date DATETIME,
    create_user VARCHAR(20),
    create_date DATETIME,
    update_user VARCHAR(20),
    update_date DATETIME,
    cancel_user VARCHAR(30),
    cancel_date DATETIME,
    cancel_reason VARCHAR(200) COMMENT '取消原因',
    depreciate_reason VARCHAR(200),
    remark VARCHAR(50),
    user_id VARCHAR(30),
    delay_fee INT(11),
    non_defend_fee INT(11),
    order_no VARCHAR(40)
}
Object t_extended_warranty{
    id INT(20) PRIMARY KEY NOT NULL COMMENT '保险自增ID' AUTO_INCREMENT,
    warranty_code VARCHAR(50) NOT NULL COMMENT '保险编号',
    insurance_code VARCHAR(255) COMMENT '保险唯一编码',
    insurance_sku VARCHAR(40) COMMENT '保险SKU',
    type INT(10) COMMENT '保险类型ID',
    sourceid TINYINT(4) COMMENT '来源类型ID',
    status TINYINT(4) COMMENT '状态， 1:未绑定,2:绑定,3:启用(激活),4:已使用,5:失效,6:待审核',
    order_flow VARCHAR(40) COMMENT '商品所属订单',
    goods_code VARCHAR(40) COMMENT '商品编号',
    goods_imei VARCHAR(80) COMMENT '商品IMEI号',
    goods_imei2 VARCHAR(80) COMMENT '商品第2个IMEI号',
    goods_name VARCHAR(6000) COMMENT '商品名称',
    goods_model VARCHAR(100) COMMENT '商品型号',
    goods_price INT(20) DEFAULT '0' COMMENT '商品价格',
    is_virtual_card TINYINT(4) COMMENT '是否是虚拟卡',
    user_id INT(20) COMMENT '用户ID',
    deliver_over_time INT(20) COMMENT '订单妥投时间',
    expiration_time INT(20) COMMENT '到期时间',
    used_time INT(20) COMMENT '使用时间',
    create_time INT(20) COMMENT '创建时间',
    modify_time INT(20) COMMENT '修改时间',
    remark TEXT COMMENT '备注',
    sale_price INT(20),
    currency VARCHAR(20) COMMENT '币种',
    pay_time INT(10) COMMENT '订单支付时间',
    insurance_tax FLOAT COMMENT '税率',
    relation_id VARCHAR(50) COMMENT '关联ID(网点ID等)',
    create_user BIGINT(20) COMMENT '创建人ID(注意和user_id区分)',
    extend_info TEXT COMMENT '拓展字段,为json格式',
    name VARCHAR(40),
    phone VARCHAR(40),
    certificateType VARCHAR(10),
    certificateCode VARCHAR(30),
    phonePhoto LONGTEXT,
    buyPhoto LONGTEXT,
    claim_num INT(10) DEFAULT '0',
    cancellation_type INT(11) DEFAULT '0' COMMENT '失效类型',
    inactive_time INT(20),
    unique_key VARCHAR(40),
    sync_number VARCHAR(30),
    sync_status TINYINT(4) DEFAULT '0' COMMENT '调用保险接口后返回 同步状态 0:未同步 1:已同步 2:同步失败',
    sync_id INT(10),
    contact_no VARCHAR(40),
    sync_active INT(11) DEFAULT '20' COMMENT '保单活动状态',
    sync_china_lasttime INT(11) COMMENT '中国区保险同步时间',
    sync_china_apply_status INT(11) DEFAULT '10' COMMENT '中国区保险投保同步状态，10：待同步，20：同步成功， 30： 同步失败',
    sync_china_cancel_status INT(11) DEFAULT '10' COMMENT '中国区保险退保同步状态，10：待同步，20：同步成功， 30： 同步失败',
    sync_china_modify_status INT(11) DEFAULT '10' COMMENT '中国区保险换保同步状态，10：待同步，20：同步成功， 30： 同步失败'
}
Object t_extended_warranty_img{
    id BIGINT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    img_url VARCHAR(100) NOT NULL,
    img_id VARCHAR(50) NOT NULL
}
Object t_extended_warranty_items{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    insurance_code VARCHAR(255) NOT NULL COMMENT '保险记录唯一code',
    shipping_last_name VARCHAR(250) COMMENT '收货人姓',
    shipping_first_name VARCHAR(250) COMMENT '收货人名',
    shipping_country VARCHAR(250) COMMENT '收货国家',
    shipping_state VARCHAR(250) COMMENT '收货州',
    shipping_city VARCHAR(250) COMMENT '收货城市',
    shipping_street VARCHAR(250),
    shipping_detail_address VARCHAR(250) COMMENT '收货详细地址',
    shipping_zip_code VARCHAR(50) COMMENT '收货邮编',
    shipping_phone VARCHAR(40) COMMENT '收货电话',
    creation_time INT(20) COMMENT '创建时间',
    billing_last_name VARCHAR(250) COMMENT '账单姓',
    billing_first_name VARCHAR(250) COMMENT '账单名',
    billing_detail_address VARCHAR(250) COMMENT '账单详细地址',
    billing_street VARCHAR(250) COMMENT '账单街道',
    billing_city VARCHAR(250) COMMENT '账单城市',
    billing_state VARCHAR(250) COMMENT '账单州',
    billing_country VARCHAR(250) COMMENT '账单国家',
    billing_zip_code VARCHAR(50) COMMENT '账单邮编',
    billing_phone VARCHAR(20) COMMENT '账单电话',
    user_email VARCHAR(250) COMMENT '用户邮箱',
    modification_time INT(20) COMMENT '最后一次修改时间',
    language VARCHAR(50) COMMENT '语言'
}
Object t_goods_detail{
    id INT(7) PRIMARY KEY NOT NULL COMMENT '售后商品详情Id' AUTO_INCREMENT,
    good_no VARCHAR(30) NOT NULL COMMENT '售后商品详情编号',
    original_good_no VARCHAR(30) COMMENT '换货单原商品详情编号',
    biz_no VARCHAR(30) COMMENT '售后受理单编号，当biz_type=1 为退货受理单，当biz_type=2 为换货受理单，当biz_type=3 为维修受理单',
    biz_type VARCHAR(1) COMMENT '1.退货 2.换货 3.维修',
    goods_code VARCHAR(30) COMMENT '商品编码',
    goods_name VARCHAR(200) COMMENT '商品名称',
    quantity INT(10) DEFAULT '0' COMMENT '商品数量',
    cat_id VARCHAR(20) COMMENT '分类ID',
    original_price INT(15) DEFAULT '0' COMMENT '商品原价',
    sale_price INT(15) DEFAULT '0' COMMENT '商品销售价',
    discount_price INT(15) DEFAULT '0' COMMENT '商品特惠价',
    update_date DATETIME COMMENT '修改时间',
    create_date DATETIME COMMENT '创建时间',
    activity_discount_price INT(11) COMMENT '参与活动优惠的总金额',
    goods_images VARCHAR(2000) COMMENT '套装时活动对应的图片',
    goods_remark VARCHAR(200) COMMENT '套装描述',
    goods_say VARCHAR(200) COMMENT '套装说明',
    goods_type VARCHAR(15) DEFAULT '1' COMMENT '商品类型  1普通商品  2 套装 缺省值为1',
    has_delay_defend INT(11) COMMENT '是否有延保 1:有延保 其它没有延保',
    delay_defend_months INT(11) COMMENT '保修到期时间',
    has_accident_defend INT(11) COMMENT '是否有意外保 1:有意外保 其它没有意外保',
    accident_defend_months INT(11) COMMENT '意外保到期日',
    reason VARCHAR(500) DEFAULT '' COMMENT '退换修原因',
    after_month INT(11) DEFAULT '0' COMMENT '商品自身保修月数',
    check_status VARCHAR(2) DEFAULT '0' COMMENT '检测状态:2：未通过1：通过0:未检测',
    isrefund INT(11) COMMENT '是否允许退货',
    refundday INT(11) COMMENT '退货天数',
    isswap INT(11) COMMENT '是否允许换货',
    swapday INT(11) COMMENT '换货天数',
    isrepair INT(11) COMMENT '是否允许维修',
    warranty INT(11) COMMENT '维修天数',
    imei VARCHAR(1700) COMMENT '手机IMEI号',
    latest_imei VARCHAR(32) COMMENT '售后更换的最新的imei号',
    latest_imei_orderflow VARCHAR(30) COMMENT '售后更换的最新的imei号对应的订单号',
    no_checked_num INT(11) UNSIGNED COMMENT '检测不通过商品数量',
    check_comments VARCHAR(1024) COMMENT 'wms检测不通过原因',
    checked_num INT(11) COMMENT '检测通过商品数量',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_insurance_detail{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    source_id VARCHAR(30) COMMENT '数据来源ID',
    source_type VARCHAR(3) COMMENT '来源类型：1-->退货; 2-->换货',
    good_no VARCHAR(30) COMMENT '商品ID',
    warranty_id INT(20) COMMENT '保险ID'
}
Object t_logistics{
    id INT(10) UNSIGNED PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    source CHAR(30) DEFAULT '' COMMENT '来源，如：rma',
    source_num CHAR(100) DEFAULT '' COMMENT '来源单据id，如：rma的num',
    service_center TINYINT(4) COMMENT '服务商',
    carrier CHAR(100) DEFAULT '' COMMENT '物流商',
    tracking_number CHAR(200) DEFAULT '' COMMENT '物流单号',
    send_type TINYINT(3) UNSIGNED COMMENT '寄出/寄回，3：寄出，2：寄回',
    delivery_status TINYINT(3) UNSIGNED DEFAULT '1' COMMENT '物流状态，1 => 'Pending', 2 => 'InfoReceived', 3 => 'InTransit', 4 => 'OutForDelivery', 5 => 'AttemptFail', 6 => 'Delivered', 7 => 'Exception', 8 => 'Expired'',
    active TINYINT(3) UNSIGNED DEFAULT '1' COMMENT 'aftership 运单活动状态，1：跟踪 0：不跟踪',
    sync_status TINYINT(3) UNSIGNED DEFAULT '1' COMMENT '同步aftership状态， 1：未同步，2：已同步',
    sync_count INT(10) UNSIGNED DEFAULT '0' COMMENT '同步aftership次数',
    create_time DECIMAL(10) COMMENT '本地创建时间',
    update_time DECIMAL(10) COMMENT '本地更新时间',
    created_at DECIMAL(10) COMMENT 'aftership创建时间',
    pickup_at DECIMAL(10) COMMENT 'aftership物流商取件时间',
    updated_at DECIMAL(10) COMMENT 'aftership更新时间',
    delivery_time DECIMAL(10) COMMENT 'aftership物流送达时间',
    tat DECIMAL(10) UNSIGNED COMMENT '物流时效',
    in_house_tat DECIMAL(10) UNSIGNED COMMENT 'RMA时效 In-House-TAT [in_house_tat = Outbound-Pickup - Inbound-Delivered]',
    `desc` TEXT COMMENT '备注'
}
Object t_package_goods_detail{
    id INT(7) PRIMARY KEY NOT NULL COMMENT '售后套装商品详情Id' AUTO_INCREMENT,
    package_good_no VARCHAR(30) NOT NULL COMMENT '售后套装商品详情编号',
    good_no VARCHAR(30) NOT NULL COMMENT '售后商品详情编号',
    original_good_no VARCHAR(30) COMMENT '换货单原商品详情编号',
    goods_code VARCHAR(30) COMMENT '套装商品编码',
    goods_name VARCHAR(200) COMMENT '套装商品名称',
    quantity INT(10) DEFAULT '0' COMMENT '套装商品数量',
    cat_id VARCHAR(20) COMMENT '套装分类ID',
    original_price INT(15) DEFAULT '0' COMMENT '套装商品原价',
    sale_price INT(15) DEFAULT '0' COMMENT '套装商品销售价',
    discount_price INT(15) DEFAULT '0' COMMENT '套装商品特惠价',
    activity_discount_price INT(11) COMMENT '参与活动优惠的总金额',
    create_date DATETIME COMMENT '创建时间',
    update_date DATETIME COMMENT '更新时间',
    goods_images VARCHAR(2000) COMMENT '套装时活动对应的图片',
    has_delay_defend INT(11),
    delay_defend_months INT(11),
    has_accident_defend INT(11),
    accident_defend_months INT(11),
    reason VARCHAR(500) DEFAULT '' COMMENT '退换修原因',
    after_month INT(11) DEFAULT '0' COMMENT '商品自身保修月数',
    check_status VARCHAR(2) DEFAULT '0' COMMENT '检测状态:2：未通过1：通过0:未检测',
    isrefund INT(11) COMMENT '是否允许退货',
    refundday INT(11) COMMENT '退货天数',
    isswap INT(11) COMMENT '是否允许换货',
    swapday INT(11) COMMENT '换货天数',
    isrepair INT(11) COMMENT '是否允许维修',
    warranty INT(11) COMMENT '维修天数',
    imei VARCHAR(1700) COMMENT '手机IMEI号',
    latest_imei VARCHAR(32) COMMENT '售后更换的最新的imei号',
    latest_imei_orderflow VARCHAR(32) COMMENT '售后更换的最新的imei号对应的订单号',
    no_checked_num INT(11) COMMENT '检测不通过商品数量',
    checked_num INT(11) COMMENT '检测通过商品数量',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_pay_detail{
    id INT(15) UNSIGNED PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    biz_type VARCHAR(1) COMMENT '业务类型',
    biz_no VARCHAR(30) NOT NULL COMMENT '业务号',
    order_flow VARCHAR(40) COMMENT '订单号',
    pay_flow VARCHAR(64) COMMENT '支付流水',
    pay_amount INT(15) COMMENT '支付金额',
    create_date DATETIME,
    update_date DATETIME,
    status VARCHAR(2) DEFAULT '1' COMMENT '支付状态'
}
Object t_refund_detail{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    biz_type VARCHAR(1) COMMENT '业务类型',
    biz_no VARCHAR(30) NOT NULL COMMENT '业务编码',
    order_flow VARCHAR(40) COMMENT '订单号',
    pay_flow VARCHAR(30) COMMENT '支付流水',
    refund_flow VARCHAR(30) COMMENT '退款流水',
    refund_reason VARCHAR(300) COMMENT '退款原因',
    refund_amount INT(15) COMMENT '退款金额',
    status VARCHAR(2) DEFAULT '1' COMMENT '状态    ',
    create_date DATETIME COMMENT '创建时间',
    update_date DATETIME COMMENT '更新时间'
}
Object t_reject{
    id INT(20) UNSIGNED PRIMARY KEY NOT NULL COMMENT '退货单ID' AUTO_INCREMENT,
    reject_no VARCHAR(30) COMMENT '退货单编码',
    reject_acceptance_no VARCHAR(30) COMMENT '退货受理单编码',
    swap_order_flow VARCHAR(40) COMMENT '换货订单编号',
    imei_no VARCHAR(30) COMMENT '手机串号',
    state VARCHAR(2) DEFAULT '11' COMMENT '退货单状态
								            1.初始状态（11：有效待分配）
								            2.便捷退货(21:待入库)
								            3.网点退货（31：网点检测通过，32：网点检测不通过）
								            4.上门退货（41：已打印快递单,42：揽件成功,43：揽件失败）
								            5.客服介入（51：等待客服处理,52：折旧入库）
								            6.',
    type VARCHAR(1) DEFAULT '1' COMMENT '退货单类型 1.网点退货单 2.上门退货单 3.便捷退货单',
    create_user VARCHAR(30) COMMENT '创建人',
    create_date DATETIME COMMENT '创建时间,默认为系统当前时间',
    update_user VARCHAR(30) COMMENT '修改人',
    update_date DATETIME COMMENT '修改时间 ',
    cancel_user VARCHAR(30) COMMENT '退货单取消人Id',
    cancel_date DATETIME COMMENT '退货单取消时间',
    cancel_reason VARCHAR(200) COMMENT '退货单取消原因',
    checker VARCHAR(20) COMMENT '检测人ID 使用客服人员工号',
    check_date DATETIME COMMENT '检测时间',
    express_no VARCHAR(30) COMMENT '快递单号',
    user_id VARCHAR(35) COMMENT '用户ID',
    original_order_flow VARCHAR(40) COMMENT '关联的源退货订单Code',
    check_status VARCHAR(1) COMMENT '检测结果：0不通过 1通过',
    refund_status SMALLINT(6) COMMENT '退款时间',
    refund_date DATETIME COMMENT '退款状态 0/null：未退款 1：已退款',
    service_code VARCHAR(1) COMMENT '服务类型',
    repair_no VARCHAR(30),
    remark VARCHAR(300),
    branch_check_remark VARCHAR(300),
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_reject_acceptance{
    id INT(20) UNSIGNED PRIMARY KEY NOT NULL COMMENT '退货受理单ID' AUTO_INCREMENT,
    reject_acceptance_no VARCHAR(30) DEFAULT '' COMMENT '退货受理单编码',
    original_order_flow VARCHAR(40) COMMENT '关联的源退货订单Code',
    swap_order_flow VARCHAR(30) COMMENT '换货订单编号',
    branch_no VARCHAR(30) COMMENT '网点编号',
    storage_address_no VARCHAR(30) COMMENT '库房地址编号(用用便捷换货受理单中记录退货的库房地址信息)',
    type VARCHAR(1) DEFAULT '1' COMMENT '退货受理单类型 1.网点受理单 2.上门受理单 3.便捷受理单',
    method VARCHAR(1) DEFAULT '1' COMMENT '退货方式 1.退货（缺省值） 2.换货导致退货',
    state VARCHAR(2) DEFAULT '11' COMMENT '1	待审核
2	待支付
3	已完成
4	已取消
',
    checker VARCHAR(20) DEFAULT '' COMMENT '审核人ID 使用客服人员工号',
    check_date DATETIME COMMENT '审核时间',
    reason VARCHAR(1000) COMMENT '退货原因',
    generate_channel VARCHAR(1) DEFAULT '1' COMMENT '1.系统生成 2.客服填写 3.客户填写',
    quantity BIGINT(20) DEFAULT '0' COMMENT '退货商品数量,缺省值为0',
    need_reject_amount BIGINT(20) DEFAULT '0' COMMENT '应退款金额,缺省值为0',
    depreciate_amount BIGINT(20) DEFAULT '0' COMMENT '折旧维修单产生的折扣金额,缺省值为0',
    used_insurce_amount BIGINT(20) COMMENT '已使用、已过期的保险金额',
    ship_price BIGINT(20) DEFAULT '0' COMMENT '运费',
    disnoship_totalamount BIGINT(20) DEFAULT '0' COMMENT '剩余商品无运费的总价',
    activity_discount_amount BIGINT(20) DEFAULT '0' COMMENT '活动总优惠金额',
    total_amount BIGINT(20) DEFAULT '0' COMMENT '原总价',
    remaind_amount BIGINT(20) DEFAULT '0' COMMENT '剩余商品金额(原订单总金额-应退款金额),缺省值为0',
    insurce_amount BIGINT(20) COMMENT '保险金额',
    depreciated_total_amount BIGINT(20) DEFAULT '0' COMMENT '成功退款的历史折旧总金额',
    had_insurance_amount BIGINT(20) COMMENT '历史保险金额',
    rejected_total_amount BIGINT(20) DEFAULT '0' COMMENT '历史成功退款的累加总金额',
    fact_reject_amount BIGINT(20) DEFAULT '0' COMMENT '实退款金额(应退款金额-折旧维修单产生的折扣金额),缺省值为0',
    original_order_total_amount BIGINT(20) DEFAULT '0' COMMENT '原订单总金额（商品总金额-优惠总金额+运费）,缺省值为0',
    original_total_discountFee BIGINT(20) DEFAULT '0' COMMENT '原订单优惠总金额(折扣金额),缺省值为0',
    original_contract_price BIGINT(20) DEFAULT '0' COMMENT '订单合约金额',
    mobile_num_price BIGINT(20) DEFAULT '0' COMMENT '手机号码金额',
    create_user VARCHAR(30) COMMENT '创建人',
    create_date DATETIME COMMENT '创建时间',
    update_user VARCHAR(30) COMMENT '修改人',
    update_date DATETIME COMMENT '修改时间',
    cancel_date DATETIME COMMENT '退货受理单取消时间',
    cancel_user VARCHAR(30) COMMENT '退货受理单取消人Id',
    cancel_reason VARCHAR(200) COMMENT '退货受理单取消原因',
    repair_no VARCHAR(30) COMMENT '折旧维修单号',
    address_no VARCHAR(30) COMMENT '退货发件人地址编号',
    user_id VARCHAR(35) COMMENT '用户ID',
    section VARCHAR(1) DEFAULT '1' COMMENT '配送时段 1 工作日休息日假日均可送货 （默认）;2 只工作日送货,休息日或假日不送;3.只休息日或假日送货;缺省1',
    appoint_date DATE COMMENT '预约时间',
    service_code VARCHAR(1) COMMENT '服务类型',
    source_type INT(10),
    remark VARCHAR(300),
    service_code_reason VARCHAR(50) COMMENT '服务类型原因',
    acceptance_check_type TINYINT(4) DEFAULT '0' COMMENT '客服审核受理单类型 开箱损:1 七天无理由退:2  七天无理由换:3 15天性能故障退:4 30天性能故障换:5  一年保修:6 非保:7',
    assignner VARCHAR(50) COMMENT '分配人',
    manual_refund_amount BIGINT(20) COMMENT '手动退款金额',
    manual_express_price BIGINT(20) COMMENT '手动退款运费',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_remote_record{
    biz_no VARCHAR(32) NOT NULL COMMENT '业务编号',
    biz_type VARCHAR(32) NOT NULL COMMENT '业务类型',
    remote_type VARCHAR(10) NOT NULL,
    last_remote_date TIMESTAMP COMMENT '最近一次调用时间',
    last_remote_result VARCHAR(10) COMMENT '最后一次调用结果',
    last_remote_errcode VARCHAR(5) COMMENT '最后一次调用错误编码',
    last_remote_errmsg VARCHAR(521) COMMENT '最后一次调用错误信息',
    remote_count INT(11) COMMENT '调用次数',
    CONSTRAINT `PRIMARY` PRIMARY KEY (biz_no, biz_type, remote_type)
}
Object t_site{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(50),
    branch_no VARCHAR(30),
    create_user VARCHAR(20),
    create_date DATETIME,
    address_detail VARCHAR(300),
    update_date DATETIME,
    tel_no VARCHAR(15),
    contact VARCHAR(20),
    province VARCHAR(100),
    city VARCHAR(100),
    area VARCHAR(100),
    street VARCHAR(500)
}
Object t_site_repair{
    id INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    branch_no VARCHAR(30),
    order_no VARCHAR(40),
    repair_no VARCHAR(30),
    repair_acceptance_no VARCHAR(30),
    has_accident_defend INT(11),
    accident_defend_time DATETIME,
    state VARCHAR(2),
    total_fee INT(11),
    total_quantity INT(11),
    pay_date DATETIME,
    check_date DATETIME,
    create_user VARCHAR(20),
    create_date DATETIME,
    update_user VARCHAR(20),
    update_date DATETIME,
    cancel_user VARCHAR(30),
    cancel_date DATETIME,
    cancel_reason VARCHAR(200) COMMENT '取消原因',
    remark VARCHAR(300),
    repair_reason VARCHAR(300),
    user_id VARCHAR(30),
    appoint_date DATETIME,
    check_status VARCHAR(1) COMMENT '检测结果：0不通过 1通过',
    service_code VARCHAR(1) COMMENT '服务类型',
    is_third_party TINYINT(4) DEFAULT '0' COMMENT '是否为第三方售后',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_site_repair_acceptance{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    repair_acceptance_no VARCHAR(30),
    order_no VARCHAR(40),
    repair_no VARCHAR(30),
    branch_no VARCHAR(30),
    has_delay_defend INT(11),
    delay_defend_time DATETIME,
    generate_channel VARCHAR(1),
    buy_channel TINYINT(4) DEFAULT '0' COMMENT '购买渠道',
    state VARCHAR(2),
    checker VARCHAR(20),
    check_date DATETIME,
    repair_reason VARCHAR(1000),
    end_date DATETIME,
    create_user VARCHAR(20),
    create_date DATETIME,
    update_user VARCHAR(20),
    update_date DATETIME,
    cancel_user VARCHAR(30),
    cancel_date DATETIME,
    cancel_reason VARCHAR(200) COMMENT '取消原因',
    remark VARCHAR(400),
    appoint_date DATETIME,
    address_no VARCHAR(30),
    user_id VARCHAR(30),
    service_code VARCHAR(1) COMMENT '服务类型',
    is_third_party TINYINT(4) DEFAULT '0' COMMENT '是否为第三方售后',
    source_type INT(10),
    third_party_order_date DATETIME COMMENT '外部订单时间',
    service_code_reason VARCHAR(50) COMMENT '服务类型原因',
    acceptance_check_type TINYINT(4) DEFAULT '0' COMMENT '客服审核受理单类型 开箱损:1 七天无理由退:2  七天无理由换:3 15天性能故障退:4 30天性能故障换:5  一年保修:6 非保:7',
    assignner VARCHAR(50) COMMENT '分配人',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_site_repair_detail{
    id INT(11) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    repair_no VARCHAR(30),
    part_id INT(11),
    part_quantity INT(11),
    part_no VARCHAR(16),
    part_price INT(11),
    part_name VARCHAR(60),
    part_type VARCHAR(16),
    part_total_fee INT(11)
}
Object t_stock{
    id INT(7) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    clerks_no VARCHAR(30) NOT NULL
}
Object t_swap_acceptance{
    id INT(7) PRIMARY KEY NOT NULL COMMENT '受理单id' AUTO_INCREMENT,
    swap_acceptance_no VARCHAR(30) NOT NULL COMMENT '换货受理单号',
    type VARCHAR(1) COMMENT '换货受理单类型
            1.网点受理单
            2.上门受理单
            3.便捷受理单
            ',
    branch_no VARCHAR(30) COMMENT 'branch_no',
    state VARCHAR(1),
    original_order_flow VARCHAR(32) COMMENT '原单编号',
    swap_order_flow VARCHAR(40) COMMENT '换货订单编号',
    return_no VARCHAR(30) COMMENT '退货单号',
    clerks_no VARCHAR(30) COMMENT '备货单号',
    repair_no VARCHAR(30) COMMENT '折扣维修单号',
    generate_channel VARCHAR(1) COMMENT '1.系统生成
            2.客服填写
            3.客户填写',
    buy_channel TINYINT(4) DEFAULT '0' COMMENT '购买渠道',
    storage_address_no VARCHAR(30) COMMENT '库房地址编号(用用便捷换货受理单中记录退货的库房地址信息)',
    addr_no VARCHAR(30) COMMENT '换货单收获地址id',
    checker VARCHAR(20) COMMENT '审核人工号',
    check_date DATETIME COMMENT '审核时间',
    create_user VARCHAR(20) COMMENT '创建人',
    create_date DATETIME NOT NULL COMMENT '创建时间',
    update_user VARCHAR(30) COMMENT '修改人',
    update_date DATETIME COMMENT '修改时间',
    cancel_user VARCHAR(30),
    cancel_date DATETIME COMMENT '换货单取消时间',
    cancel_reason VARCHAR(200) COMMENT '换货单取消原因',
    appoint_date DATE COMMENT '预约时间',
    remark VARCHAR(300),
    user_id VARCHAR(35) COMMENT '用户ID',
    section VARCHAR(5),
    reason VARCHAR(1000) COMMENT '退货原因',
    addr_id INT(20) COMMENT '用户中心地址主键',
    service_code VARCHAR(1) COMMENT '服务类型',
    is_third_party TINYINT(4) DEFAULT '0' COMMENT '是否为第三方售后',
    source_type INT(10),
    attach_path VARCHAR(200) COMMENT '附件链接',
    third_party_order_date DATETIME COMMENT '外部订单时间',
    service_code_reason VARCHAR(50) COMMENT '服务类型原因',
    acceptance_check_type TINYINT(4) DEFAULT '0' COMMENT '客服审核受理单类型 开箱损:1 七天无理由退:2  七天无理由换:3 15天性能故障退:4 30天性能故障换:5  一年保修:6 非保:7',
    assignner VARCHAR(50) COMMENT '分配人',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object t_swap_original_goods{
    id INT(7) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    original_good_no VARCHAR(30) NOT NULL COMMENT '原商品编码',
    swap_acceptance_no VARCHAR(30) NOT NULL COMMENT '换货受理单号',
    goods_code VARCHAR(30) COMMENT '商品编码',
    goods_name VARCHAR(200) COMMENT '商品名称',
    quantity INT(10) DEFAULT '0' COMMENT '数量',
    cat_id VARCHAR(20),
    original_price INT(15) DEFAULT '0' COMMENT '原价',
    sale_price INT(15) DEFAULT '0' COMMENT '售价',
    discount_price INT(15) DEFAULT '0' COMMENT '折扣价',
    activity_discount_price INT(11) COMMENT '实际折扣价',
    goods_images VARCHAR(2000) COMMENT '图片',
    goods_remark VARCHAR(200) COMMENT '备注',
    goods_say VARCHAR(200),
    goods_type VARCHAR(15) DEFAULT '1' COMMENT '商品类型',
    create_date DATETIME COMMENT '创建时间',
    update_date DATETIME COMMENT '更新时间',
    reason VARCHAR(200) COMMENT '原因',
    imei VARCHAR(1700) COMMENT '手机IMEI号',
    latest_imei VARCHAR(32) COMMENT '售后更换的最新的imei号',
    latest_imei_orderflow VARCHAR(40) COMMENT '售后更换的最新的emei号对应的订单号',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object v_common_repair{
    user_id VARCHAR(30),
    order_no VARCHAR(14),
    repair_acceptance_no VARCHAR(30),
    source_no VARCHAR(30),
    repair_no VARCHAR(30),
    create_date DATETIME,
    state VARCHAR(2),
    branch_no VARCHAR(30),
    repair_type VARCHAR(1)
}
Object worksheet{
    worksheetcode VARCHAR(40) PRIMARY KEY NOT NULL,
    bewrite LONGTEXT,
    busicateg1 INT(11),
    busicateg2 INT(11),
    busicateg3 INT(11),
    busicateg4 INT(11),
    createtime DATETIME NOT NULL,
    customerid VARCHAR(80),
    holder VARCHAR(40),
    modifytime DATETIME,
    sourceid VARCHAR(80) NOT NULL,
    sourcetype VARCHAR(20) NOT NULL,
    status VARCHAR(12) NOT NULL
}
Object worksheet_log{
    wslogcode VARCHAR(40) PRIMARY KEY NOT NULL,
    content LONGTEXT,
    createtime DATETIME NOT NULL,
    createuser VARCHAR(40) NOT NULL,
    logtype VARCHAR(12) NOT NULL,
    worksheetcode VARCHAR(40)
}
Object worksheet_memo{
    wsmemocode VARCHAR(40) PRIMARY KEY NOT NULL,
    content LONGTEXT,
    createtime DATETIME NOT NULL,
    createuser VARCHAR(40) NOT NULL,
    worksheetcode VARCHAR(40)
}
Object worksheet_reply{
    wsreplycode VARCHAR(40) PRIMARY KEY NOT NULL,
    content TEXT NOT NULL,
    createtime DATETIME NOT NULL,
    createuser VARCHAR(40) NOT NULL,
    replytype VARCHAR(12) NOT NULL,
    worksheetcode VARCHAR(40)
}
Object worksheet_warning{
    warningid VARCHAR(20) PRIMARY KEY NOT NULL,
    createtime DATETIME,
    descr VARCHAR(900),
    disabled TINYINT(4),
    emails VARCHAR(800),
    maxnumber INT(11),
    modifytime DATETIME,
    period INT(11),
    sourcetype VARCHAR(20) NOT NULL,
    status VARCHAR(12) NOT NULL
}
Object gs_attachment{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    source_id VARCHAR(80) COMMENT '来源主键',
    source_type SMALLINT(6) COMMENT '来源类型 10：合作方上传 20：用户自动上传',
    file_key VARCHAR(200) COMMENT '上传文件的唯一key',
    file_name VARCHAR(200) COMMENT '真实文件名',
    file_size BIGINT(64) COMMENT '文件大小',
    create_user VARCHAR(100),
    create_time DATETIME,
    url_prefix VARCHAR(600) COMMENT 'url前缀',
    url_suffix VARCHAR(600) COMMENT 'url前缀'
}
Object gs_logistics_anomaly{
    lma_sheet_id VARCHAR(40) PRIMARY KEY NOT NULL COMMENT '物流异常单号',
    cancel_reason VARCHAR(600) COMMENT '取消原因',
    carrier VARCHAR(50) COMMENT '物流商',
    complaint_no VARCHAR(100) COMMENT '投诉单号',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    customer_id VARCHAR(40) COMMENT '用户id',
    delivery_status INT(4) COMMENT '物流状态',
    memo VARCHAR(600) COMMENT '备注',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    package_status INT(4) COMMENT '包裹状态',
    premium_amount INT(4) COMMENT '税费金额',
    premium_currency VARCHAR(50) COMMENT '税费币种',
    premium_status INT(4) COMMENT '税费状态',
    request_time DATETIME COMMENT '请求时间',
    service_zone VARCHAR(50) COMMENT '服务区域',
    source_id VARCHAR(40) COMMENT '来源id',
    source_type INT(4) COMMENT '来源类型',
    status INT(4) COMMENT '状态',
    ticket_no VARCHAR(100) COMMENT '工单编号',
    tracking_no VARCHAR(100) COMMENT '物流单号',
    type INT(4) COMMENT '单据类型',
    sign_in_time VARCHAR(100) COMMENT '订单签收时间',
    delivery_time VARCHAR(100) COMMENT '订单发货时间',
    house_code VARCHAR(100) COMMENT '网点或者仓库编号',
    house_name VARCHAR(255) COMMENT '网点或者仓库名称',
    email VARCHAR(255) COMMENT '邮件地址',
    remark VARCHAR(600) COMMENT '核实备注',
    verify_result INT(4) COMMENT '核实结果',
    reissue_carrier INT(4) COMMENT '重发物流商',
    reissue_tracking_no VARCHAR(100) COMMENT '重发物流单号',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    reissue_time_end DATETIME,
    reissue_time_start DATETIME
}
Object gs_logistics_anomaly_address{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    addr_city VARCHAR(40) COMMENT '市',
    addr_city_name VARCHAR(300) COMMENT '市名称',
    addr_detail VARCHAR(900) COMMENT '详细地址',
    addr_distr VARCHAR(40) COMMENT '区',
    addr_distr_name VARCHAR(300) COMMENT '区名称',
    addr_prov VARCHAR(40) COMMENT '省',
    addr_prov_name VARCHAR(300) COMMENT '省名称',
    addr_street VARCHAR(40) COMMENT '街',
    addr_street_name VARCHAR(600) COMMENT '街名称',
    addr_type INT(4) COMMENT '地址类型 10:入库 20:出库',
    country VARCHAR(40) COMMENT '国家',
    country_name VARCHAR(300) COMMENT '国家名称',
    customer_id VARCHAR(80) COMMENT '用户id',
    customer_name VARCHAR(300) COMMENT '用户名称',
    email VARCHAR(300) COMMENT 'email',
    phone_number VARCHAR(60) COMMENT '联系电话',
    post_code VARCHAR(60) COMMENT '邮编',
    receiver_first_name VARCHAR(255) COMMENT ' 收货人名字',
    receiver_last_name VARCHAR(255) COMMENT ' 收货人姓',
    receiver_name VARCHAR(300) COMMENT '收货人名称',
    source_id VARCHAR(40) COMMENT '来源主键',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object gs_logistics_anomaly_goods{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    goods_code VARCHAR(40) COMMENT '商品编码',
    goods_name VARCHAR(300) COMMENT '商品名称',
    goods_status INT(4) COMMENT '物品状态：Extra，Missing，Damaged',
    imei VARCHAR(40) COMMENT '原imei号1',
    imei2 VARCHAR(40) COMMENT '原imei号2',
    order_qty INT(11) COMMENT '订单数量',
    original_price INT(11) COMMENT '原价金额',
    product_date DATETIME COMMENT '商品生产日期',
    requirement INT(4) COMMENT '要求',
    source_id VARCHAR(40),
    submit_qty INT(11) COMMENT '提交数量',
    treatment INT(4) COMMENT '处理方式',
    verify_result INT(4) COMMENT '审核结果',
    status INT(4) COMMENT '处理状态 0:未处理 10:正在处理 20:已处理',
    discount_amount INT(11) COMMENT '折扣金额',
    d_create_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
    d_update_time TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
}
Object gs_order_rel{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键，自增' AUTO_INCREMENT,
    new_order VARCHAR(60) COMMENT '新订单号',
    new_order_type SMALLINT(6) COMMENT '新订单号类型',
    original_order VARCHAR(60) COMMENT '原订单号',
    source_id VARCHAR(40) COMMENT '来源单号',
    source_type SMALLINT(6) COMMENT '来源类型 10：rma 20:lma',
    remark VARCHAR(600) COMMENT '备注',
    create_time DATETIME COMMENT '创建时间',
    order_reason SMALLINT(6) COMMENT '订单原因',
    status SMALLINT(6) DEFAULT '10' COMMENT '状态 10：Active 20:Inactive'
}
Object gs_refund_sheet{
    refund_sheet_id VARCHAR(255) PRIMARY KEY NOT NULL,
    create_time DATETIME,
    create_user VARCHAR(255),
    currency VARCHAR(255),
    country VARCHAR(255) COMMENT '国家',
    memo VARCHAR(6000) COMMENT '备注',
    modify_time DATETIME,
    modify_user VARCHAR(40),
    order_amount INT(11),
    order_no VARCHAR(255),
    payer VARCHAR(255),
    payment_time DATETIME,
    paypal_no VARCHAR(255),
    product_type_descr VARCHAR(255),
    refund_amount INT(11),
    refund_time DATETIME,
    source_id VARCHAR(40) COMMENT '来源主键',
    status INT(11),
    type INT(11),
    auto_flag SMALLINT(6) COMMENT '是否是自动创建 0：手动创建 1：自动创建',
    virtual_refund_flag SMALLINT(6) DEFAULT '0' COMMENT '是否假退款',
    source_type TINYINT(4) COMMENT '来源类型 10:RMA 20:LMA'
}
Object gs_rma_partner_import{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    rma_no VARCHAR(40) COMMENT 'RMA单号',
    order_number VARCHAR(40) COMMENT '服务商单号',
    pp_repair_price_curr VARCHAR(40) COMMENT '币种',
    oow_process VARCHAR(100) COMMENT 'oow',
    incoming_imei1 VARCHAR(40) COMMENT 'imei1',
    incoming_imei2 VARCHAR(40) COMMENT 'imei2',
    incoming_software_version VARCHAR(600) COMMENT '软件版本',
    customer_report_fault VARCHAR(2000) COMMENT '客户报告问题',
    malfunction_symptom VARCHAR(2000) COMMENT '错误描述',
    malfunction_cause VARCHAR(2000) COMMENT '原因描述',
    out_imeino VARCHAR(40) COMMENT '新imei',
    carrier VARCHAR(1000) COMMENT '物流商',
    inbound_tracking_no VARCHAR(1000) COMMENT '客户寄入物流单号',
    outbound_tracking_no VARCHAR(1000) COMMENT '服务商寄出物流单号',
    out_software_version VARCHAR(600) COMMENT '新软件版本',
    replacement_part_sku1 VARCHAR(40) COMMENT '备件1代码',
    replacement_part_name1 VARCHAR(300) COMMENT '备件1名称',
    replacement_part_sku2 VARCHAR(40) COMMENT '备件2代码',
    replacement_part_name2 VARCHAR(300) COMMENT '备件2名称',
    replacement_part_sku3 VARCHAR(40) COMMENT '备件3代码',
    replacement_part_name3 VARCHAR(300) COMMENT '备件3名称',
    replacement_part_sku4 VARCHAR(40) COMMENT '备件4代码',
    replacement_part_name4 VARCHAR(300) COMMENT '备件4名称',
    replacement_part_sku5 VARCHAR(40) COMMENT '备件5代码',
    replacement_part_name5 VARCHAR(300) COMMENT '备件5名称',
    replacement_part_sku6 VARCHAR(40) COMMENT '备件6代码',
    replacement_part_name6 VARCHAR(300) COMMENT '备件6名称',
    replacement_part_sku7 VARCHAR(40) COMMENT '备件7代码',
    replacement_part_name7 VARCHAR(300) COMMENT '备件7名称',
    replacement_part_sku8 VARCHAR(40) COMMENT '备件8代码',
    replacement_part_name8 VARCHAR(300) COMMENT '备件8名称',
    replacement_part_sku9 VARCHAR(40) COMMENT '备件9代码',
    replacement_part_name9 VARCHAR(300) COMMENT '备件9名称',
    replacement_part_sku10 VARCHAR(40) COMMENT '备件10代码',
    replacement_part_name10 VARCHAR(300) COMMENT '备件10名称',
    replacement_part_sku11 VARCHAR(40) COMMENT '备件11代码',
    replacement_part_name11 VARCHAR(300) COMMENT '备件11名称',
    replacement_part_sku12 VARCHAR(40) COMMENT '备件12代码',
    replacement_part_name12 VARCHAR(300) COMMENT '备件12名称',
    replacement_part_sku13 VARCHAR(40) COMMENT '备件13代码',
    replacement_part_name13 VARCHAR(300) COMMENT '备件13名称',
    replacement_part_sku14 VARCHAR(40) COMMENT '备件14代码',
    replacement_part_name14 VARCHAR(300) COMMENT '备件14名称',
    replacement_part_sku15 VARCHAR(40) COMMENT '备件15代码',
    replacement_part_name15 VARCHAR(300) COMMENT '备件15名称',
    imei_in VARCHAR(40) COMMENT '退换imei',
    first_symptom_code VARCHAR(2000) COMMENT '初检结果',
    second_symptom_code VARCHAR(2000) COMMENT '复检结果',
    visual_status VARCHAR(40) COMMENT '外观',
    inspection VARCHAR(40) COMMENT '检测结果',
    type INT(11) COMMENT '导入类型',
    not_match_msg VARCHAR(2000) COMMENT '匹配不上错误信息'
}
Object gs_rma_sheet_ext{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    complete_time DATETIME,
    inspect_time DATETIME,
    modify_user VARCHAR(40),
    rmaSheetId VARCHAR(255),
    walk_in_time DATETIME COMMENT '送修时间',
    pick_up_time DATETIME COMMENT '取机时间',
    repaired_time DATETIME COMMENT '维修结束时间'
}
Object gs_rma_spareparts_report{
    report_id VARCHAR(20) PRIMARY KEY NOT NULL,
    service_node_code VARCHAR(80) COMMENT '网点编号',
    service_node_name VARCHAR(200) COMMENT '网点名称',
    status TINYINT(4) COMMENT '状态 10:未同步wms 20:已同步wms',
    total_parts_qty INT(11) COMMENT '备件总数量',
    total_rma_qty INT(11) COMMENT 'RMA总数量',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT ' 创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人'
}
Object gs_rma_spareparts_report_detail{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    report_id VARCHAR(20) NOT NULL COMMENT '报表id',
    goods_code VARCHAR(40) COMMENT '商品编号',
    goods_name VARCHAR(255) COMMENT '商品名称',
    consumption_qty INT(11) COMMENT '消耗数量',
    create_time DATETIME,
    create_user VARCHAR(255)
}
Object gs_sql_export{
    sql_export_id VARCHAR(20) PRIMARY KEY NOT NULL COMMENT '主键ID',
    name VARCHAR(100) COMMENT '名称',
    instruction VARCHAR(300) COMMENT '说明',
    type INT(11) COMMENT '类型',
    regions VARCHAR(100) COMMENT '区域',
    time_interval INT(11) COMMENT '时间间隔',
    sql_content VARCHAR(20000) COMMENT 'sql的内容',
    is_deleted INT(11) COMMENT '是否已删除',
    createtime DATETIME COMMENT '添加时间',
    createuser VARCHAR(40) COMMENT '添加人'
}
Object gs_tag_config{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    remark VARCHAR(300) COMMENT '备注',
    source_id VARCHAR(40) COMMENT '来源主键',
    source_type SMALLINT(6) COMMENT '来源类型 10:LMA',
    tag_key VARCHAR(50) COMMENT 'key值',
    tag_value VARCHAR(100) COMMENT 'value值'
}
Object t_extended_middleware{
    id INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    uuid VARCHAR(100) COMMENT '唯一编号， uuid',
    warranty_code VARCHAR(50) COMMENT '保险编号',
    insurance_sku VARCHAR(50) COMMENT '保险SKU',
    insurance_name VARCHAR(200) COMMENT '保险名称',
    sale_price INT(20) COMMENT '保险价格快照',
    currency VARCHAR(20) COMMENT '币种',
    pay_time INT(10) COMMENT '订单支付时间',
    insurance_code VARCHAR(255) COMMENT '保险唯一编码',
    type INT(11) COMMENT '保险类型ID, 101:半年延长保类型,102:一年延长保类型,201:一年意外保类型,302:一年屏碎保类型,312:半年屏碎保类型,202:海外18个月意外保类型,203:海外24个月意外保类型,103:海外12个月延长保类型',
    sourceid TINYINT(4) COMMENT '来源类型ID',
    status TINYINT(4) COMMENT '状态 1:Inactive, 2:Actived, 3:Pending refund, 4:Refunded',
    sync_status TINYINT(4) COMMENT '同步保险主表状态 1：未同步；2：已同步；3：同步失败',
    order_flow VARCHAR(50) COMMENT '商品所属订单',
    goods_imei VARCHAR(80) COMMENT '商品IMEI号',
    goods_imei2 VARCHAR(80) COMMENT '商品第2个IMEI号',
    deliver_over_time INT(11) COMMENT '订单妥投时间, 保险开始时间',
    expiration_time INT(11) COMMENT '到期时间',
    dispatch_time INT(11) COMMENT 'wms订单出库时间',
    create_time INT(11) COMMENT '创建时间',
    modify_time INT(11) COMMENT '修改时间',
    name VARCHAR(50) COMMENT '联系人',
    phone VARCHAR(50) COMMENT '联系电话',
    email VARCHAR(50) COMMENT 'email',
    remark TEXT COMMENT '备注'
}
Object t_extended_warranty_notices{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '自增主键' AUTO_INCREMENT,
    source_no VARCHAR(50) NOT NULL COMMENT '来源单号',
    source_id INT(11) NOT NULL COMMENT '来源ID',
    create_time BIGINT(20) NOT NULL COMMENT '创建时间',
    modify_time BIGINT(20) NOT NULL COMMENT '最新更新时间',
    source_status INT(11) DEFAULT '1' NOT NULL COMMENT '来源单据状态',
    sync_status INT(11) DEFAULT '1' NOT NULL COMMENT '同步状态',
    sync_num INT(11) DEFAULT '0' NOT NULL COMMENT '同步次数'
}
Object yiilog{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    level VARCHAR(128),
    category VARCHAR(128),
    logtime INT(11),
    message LONGTEXT
}
Object gs_snowball{
    id INT(11) PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    pcba VARCHAR(100),
    cplc VARCHAR(300),
    imei1 VARCHAR(100),
    imei2 VARCHAR(100),
    meid VARCHAR(100),
    true_imei VARCHAR(100) COMMENT '开卡使用的imei数据，后续查询使用',
    device_model VARCHAR(300),
    delete_time DATETIME
}
Object gs_suggestion{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contact VARCHAR(300) COMMENT '建议人联系方式',
    title VARCHAR(300) COMMENT '建议标题',
    content VARCHAR(3000) COMMENT '建议内容',
    handle_opinion VARCHAR(1000) COMMENT '处理意见',
    status SMALLINT(255) COMMENT '状态，10：待处理 20：处理中 30：挂起 40：拒绝 50：已处理',
    create_user VARCHAR(80) COMMENT '创建人',
    create_time DATETIME COMMENT '创建时间',
    modify_user VARCHAR(80) COMMENT '修改人',
    modify_time DATETIME COMMENT '修改时间'
}
Object gs_data_dic_classify{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    classify_key VARCHAR(300) COMMENT '分类唯一key',
    classify_name VARCHAR(200) COMMENT '分类名称',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    level INT(11) COMMENT '级别',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    parent_id INT(11) COMMENT '父级节点id',
    path VARCHAR(300) COMMENT '分类路径',
    status SMALLINT(6) COMMENT '状态 10：激活 20：失效',
    weight INT(11) COMMENT '权重',
    key_classify_key VARCHAR(200) COMMENT 'key应用的分类key',
    value_classify_key VARCHAR(300) COMMENT 'value应用的分类key',
    language_optional SMALLINT(6) COMMENT '语言是否可选'
}
Object gs_data_dictionary{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    language VARCHAR(40) COMMENT '语言',
    path VARCHAR(200) COMMENT '国际化枚举路径',
    path_key VARCHAR(100) COMMENT '枚举的key',
    path_value VARCHAR(200) COMMENT '枚举的value',
    status INT(4) COMMENT '状态 10:激活 20:未激活',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '修改时间',
    modify_user VARCHAR(40) COMMENT '修改人',
    weight INT(11) COMMENT '权重'
}
Object gs_doa_sheet{
    doa_sheet_id VARCHAR(40) PRIMARY KEY NOT NULL COMMENT 'DOA单号',
    servicenode_code VARCHAR(40) COMMENT '网点编号',
    warehouse_code VARCHAR(40) COMMENT '仓库编码',
    sku VARCHAR(40) COMMENT 'sku',
    sku_name_en VARCHAR(300) COMMENT 'sku英文名',
    sku_name_cn VARCHAR(300) COMMENT 'sku中文名',
    apply_qty INT(11) COMMENT '申请数量',
    type SMALLINT(255) COMMENT 'DOA类型，10：Physical Damage  20：Functional Damage',
    remark VARCHAR(3000) COMMENT '备注',
    status INT(255) COMMENT 'DOA单状态',
    reject_reason VARCHAR(3000) COMMENT '拒绝原因',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(80) COMMENT '创建人',
    modify_time DATETIME COMMENT '修改时间',
    modify_user VARCHAR(80) COMMENT '修改人'
}
Object gs_rma_spareparts{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    source_id VARCHAR(40) COMMENT '来源id主键',
    treatment_type TINYINT(4) COMMENT '保内保外类型 10:保外 12:保内',
    sku_code VARCHAR(40) COMMENT 'sku编号',
    apply_price INT(11) COMMENT '领退料价格',
    status TINYINT(4) COMMENT '状态',
    apply_currency VARCHAR(40) COMMENT '申请币种',
    quotation_price INT(11) COMMENT ' 网点给用户报价',
    quotation_currency VARCHAR(40),
    partner VARCHAR(40) COMMENT '服务商',
    service_node_code VARCHAR(20) COMMENT '网点编号',
    cn_name VARCHAR(200) COMMENT '中文名称',
    en_name VARCHAR(200) COMMENT '英文名称',
    machine_types VARCHAR(40) COMMENT 'SKU机型，所个用逗号分隔',
    type VARCHAR(40) COMMENT 'SKU类型 主板、耗材等',
    value INT(11) COMMENT 'SKU高低价值 10:低价值 20:高价值',
    warehouse_code VARCHAR(40) COMMENT '备件当前所在仓库编码',
    apply_sheet_id VARCHAR(40) COMMENT '退料申请单id',
    apply_sheet_id2 VARCHAR(40) COMMENT '退料申请单id2',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    min_pck_qty INT(11) COMMENT '最小包装数量',
    rma_complete_time DATETIME COMMENT 'RMA完成时间',
    tmp_id INT(11) COMMENT '历史数据迁移时候的id',
    tmp_quotataion_currency VARCHAR(20)
}
Object gs_spareparts_packaging_goods{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    apply_sheet_id VARCHAR(3000) COMMENT '备件申请单id',
    approved_count INT(11) COMMENT '已审核数量',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(255) COMMENT '创建人',
    goods_code VARCHAR(40) COMMENT 'SKU编号',
    goods_en_name VARCHAR(200) COMMENT 'SKU英文名称',
    goods_name VARCHAR(200) COMMENT 'SKU名称',
    machine_types VARCHAR(40) COMMENT 'SKU机型',
    min_pck_qty INT(11) COMMENT '最小打包数量',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    packaged_count INT(11) COMMENT '已打包数量',
    stock_sheet_id VARCHAR(40) COMMENT '发货单号',
    type VARCHAR(40) COMMENT 'SKU类型',
    value INT(11) COMMENT 'SKU高低价值 10:低价值 20:高价值',
    version INT(11),
    received_count INT(11) COMMENT '已收货数量',
    rollback_count INT(11) DEFAULT '0' COMMENT '打回数量'
}
Object gs_spareparts_sku{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    sku_code VARCHAR(40) COMMENT 'SKU编码',
    cn_name VARCHAR(200) COMMENT 'SKU中文名称',
    en_name VARCHAR(200) COMMENT 'SKU英文名称',
    type VARCHAR(40) COMMENT '类型 主板或者耗材等',
    machine_types VARCHAR(40) COMMENT '机型',
    value INT(4) COMMENT '价值 10:低价值 20:高价值',
    costs INT(11) COMMENT '成本价',
    tax_currency VARCHAR(40) COMMENT '成本币种',
    remark VARCHAR(600) COMMENT '备注',
    status INT(4) COMMENT '状态 10:激活 20:失效',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人',
    weight INT(11),
    hsn VARCHAR(128) COMMENT '海关编码',
    tax_rate DECIMAL(16,5) COMMENT 'sku税率'
}
Object gs_spareparts_sku_price{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    sku_code VARCHAR(100) COMMENT 'SKU编号',
    partner VARCHAR(40) COMMENT '服务商',
    apply_currency VARCHAR(40) COMMENT '备件申请币种',
    apply_price INT(11) COMMENT '备件申请价格',
    quotation_currency VARCHAR(40) COMMENT '网点给用户报价币种',
    quotation_price INT(11) COMMENT '网点给用户报价',
    min_pck_qty INT(11) COMMENT '最小包装数量',
    status INT(4) COMMENT '状态 10:激活 20:失效',
    create_time DATETIME COMMENT '创建时间',
    create_user VARCHAR(40) COMMENT '创建人',
    modify_time DATETIME COMMENT '更新时间',
    modify_user VARCHAR(40) COMMENT '更新人'
}
Object gs_spareparts_warearea{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    warehouse_code VARCHAR(32) COMMENT '仓库编码',
    warehouse_name VARCHAR(40) COMMENT '仓库名称',
    area_code VARCHAR(32) COMMENT '库区编码',
    area_name VARCHAR(40) COMMENT '库区名称',
    name_temp VARCHAR(255)
}
Object gs_spareparts_warehouse{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    warehouse_code VARCHAR(80) COMMENT '仓库编号',
    warehouse_name VARCHAR(255) COMMENT '仓库编号'
}
Object tmp_malfunc{
    no VARCHAR(255),
    code VARCHAR(255),
    type VARCHAR(255),
    descr VARCHAR(255)
}
Object gs_invoice_serial{
    id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    service_node_code VARCHAR(32) COMMENT '网点号',
    money_year VARCHAR(32) COMMENT '财年',
    serial_no INT(11) COMMENT '流水号',
    order_no VARCHAR(64) NOT NULL COMMENT '订单号',
    invoice_no VARCHAR(64) NOT NULL COMMENT '发票号'
}
@enduml