@startuml

订单 "1" -down- "1" 订单收货地址
订单 "1" -left- "0..*" 订单活动信息
订单 "1" -up- "0..*" 订单支付

订单 "1" ------right----- "1..*" 订单商品
订单 "1" -down- "1" 订单发票
订单 "1" -- "0..*" 订单退款

订单商品 "1" --right-- "0..1" 订单套装商品
付款单 "1" -right- "1" 付款流水
付款单 "1" -left- "1" 订单支付
付款单 "1" -up- "0..*" 退款受理单

Object 退款受理单{

}
Object 付款单{

}

Object 付款流水{
    订单号
    交易流水
}

Object 购物车{
}


Object 订单活动信息{
    订单号
    活动类型
    优惠ID
}
Object 订单日志{
}

Object 订单收货地址{
}

Object 订单商品{
    订单号
    订单明细编号
    Sku
    数量
    价格
    折扣
    套装编码
    是否虚拟商品
    逻辑库存类型
    是否可单独发货
    发货仓库
    商品状态
    运单号
    物流渠道
}
Object 订单发票{
    发票类型
    抬头
}
Object 订单{
    订单号
    订单类型
    订单状态
    支付状态
    库存状态
    逆向状态
    锁定标识
    推送标识
}
Object 订单支付{
    order_flow
    pay_flow
}

Object 订单套装商品{

}

Object 订单退款{

}


@enduml