@startuml

state 订单退货 {
[*]-->已寄出
  已寄出 --> 已收货
  已收货 -left-> 质检不通过
  已收货 -> hold:部分收货
  质检不通过-->已入库:客服协商接受折损
  质检不通过-down-->仓库拒收:客服协商不接受折损
  已收货-down-->已入库:质检通过
  hold-->已入库:余货质检通过
}

state 订单退款 {
  已入库-->已退款
}

@enduml