@startuml
[*] --> 订单生成
' 订单生成 --> 订单支付
' 订单支付--> 订单生产
' 订单生产 --> 订单配送
' 订单配送 --> 订单完成


state 订单生成 {
    待审核 -> 锁定: 客服锁定
    锁定 -> 待支付
    待审核 -> 待支付
}


state 订单支付 {
    待支付 --> 已确认:支付完成

}

state 订单生产 {
  已确认 -> 未分配:订单推送
  未分配 -> 已分配
  已分配 -> 已打印
  未分配 --> 仓库锁定
  已分配 --> 仓库锁定
  已打印 --> 仓库锁定
  仓库锁定 --> 已打印:解锁
  仓库锁定 --> 已分配:解锁
  仓库锁定 --> 未分配:解锁
}

state 订单配送 {
  已打印-> 已出库
  }

state 订单完结 {
  已出库-->已签收
  已出库-->已拒收
  待支付 --> 已取消:超时
  锁定 --> 已取消 : 客服判定
  待审核 --> 已取消: 系统或人工审核

}

state 订单退款 {
  已确认 --> 已退款
  已取消-->已退款:支付后取消
  已拒收 --> 已退款
}

@enduml