@startuml

state 订单换货 {
[*]-->已寄出
  已寄出 --> 已收货
  已收货 -left-> 质检不通过
  已收货 --> hold:部分收货
  质检不通过-->待支付:客服协商接受折损
  待支付-->已入库:支付
  质检不通过-down-->仓库拒收:客服协商不接受折损
  已收货-down-->已入库:质检通过
  hold-->已入库:余货质检通过
  hold-->质检不通过
}

state 订单生成 {
  已入库-->已确认
}

state 订单生产 {
  已确认 -> 未分配:订单推送
  未分配 -> 已分配
  已分配 -> 已打印
  未分配 --> 仓库锁定
  已分配 --> 仓库锁定
  已打印 --> 仓库锁定
  仓库锁定 --> 已打印:解锁
  仓库锁定 --> 已分配:解锁
  仓库锁定 --> 未分配:解锁
}

state 订单配送 {
  已打印-> 已出库
}

state 订单完结 {
  已出库-->已签收
  已出库-->已拒收
}
@enduml