@startuml

left to right direction
actor 用户

rectangle 订单{
用户 -->(提交普通订单)
    (提交普通订单)-->(保存订单上下文)
    (提交普通订单)-->(计算订单价格)
    (提交普通订单)-->(使用券和邀请码)
    (提交普通订单)-->(路由占用库存)
    (提交普通订单)--> (订单写入Codis)
    (提交普通订单)-->(异步删除下单成功的订单上下文)



用户 -->(提交抢购订单)

用户 -->(提交第三方电商订单)
    (提交第三方电商订单)-->(生成第三方订单发货单)
    (提交第三方电商订单)--> (下单生成发票)


用户 -->(支付订单)


用户 -->(取消订单)
    (取消订单)-->(取消订单发货单)
    (取消订单)-->(取消订单作废国内发票)
    (取消订单)-->(发送订单取消邮件)
    (取消订单)-->(发送订单取消短信)
    (取消订单)-->(取消订单生成退款单)
    (取消订单)-->(通知抢购回收库存)


用户 -->(修改收货地址)
用户 -->(修改账单地址)
用户 -->(修改订单发票)
用户 -->(查看订单发票)
用户 -->(下载订单发票)
用户 -->(查看订单详情)
用户 -->(查看我的订单)
用户-->(以旧换新)
    以旧换新-->(以旧换新生成退款单)
}

newpage
left to right direction
actor 订单付款消息

rectangle 订单{
订单付款消息 -->(订单付款完成)
    (订单付款完成)-->(发送付款成功邮件)
    (订单付款完成)-->(修改抢购订单抢购Redis数据)
    (订单付款完成)-->(标记付款为重复)
    (订单付款完成)-->(标记订单重复付款)
    (订单付款完成)-->(修改付款记录为重复付款)
    (订单付款完成)-->(取消挂起支付异常订单)

订单付款消息 -->(订单付款Review)
订单付款消息 -->(订单付款Pending)
    订单付款Review-->(挂起支付异常订单)
    订单付款Pending-->(挂起支付异常订单)
}


newpage
left to right direction
actor 订单定时器
rectangle 订单{
订单定时器->(拉取普通订单)
    拉取普通订单-->(审核订单是否为黄牛订单)
    拉取普通订单-->(保存订单到DB)
订单定时器->(返还下单失败的券和邀请码)

订单定时器->(拉取抢购订单)
    拉取抢购订单-->(通知抢购回收库存)
    拉取抢购订单-->(计算价格使用券)

订单定时器-->(推送抢购订单发货单)
订单定时器-->(推送普通订单发货单)
    推送抢购订单发货单-->(更新商品税费)

订单定时器-->(推送第三方电商订单发货单)

订单定时器-->(发送下单1小时未支付邮件)
订单定时器-->(发送下单3小时未支付邮件)
订单定时器-->(取消超时未支付的订单)
}


newpage

left to right direction
actor 订单发货单消息
rectangle 订单发货单 {
订单发货单消息 -->(发货单已分配)

订单发货单消息 ->(发货单已出库)
    发货单已出库 -->(更新包裹出库履约)
    发货单已出库-->(发送包裹出库邮件)
    发货单已出库-->(发送包裹出库短信)

订单发货单消息 ->(发货单已签收)
    发货单已签收-->(发送包裹签收邮件)
    发货单已签收-->(发送包裹签收短信)

订单发货单消息 ->(发货单拒收入库)
    发货单拒收入库 -->(更新包裹拒收入库履约)
    发货单拒收入库-->(包裹拒收生成退款单)
}

newpage
left to right direction
actor 客服
rectangle 订单{
客服 ---->(检索订单)
客服 -->(查看订单详情)
客服 -->(添加操作日志)
客服 -->(修改收货地址)

客服 -->(修改账单地址)
客服 -->(取消转已支付)
    取消转已支付-->(更新路由信息)
    取消转已支付-->(作废老发货单，增加新发货单)

客服 --> (作废付款)
    作废付款-->(作废付款生成退款单)

客服  -->(取消重复付款)
   取消重复付款-->(重复付款生成退款单)
客服 -->(发送已付款邮件)
客服 -->(重置争议付款)
客服 -->(挂起订单)
客服 -->(取消挂起订单)

}

newpage
left to right direction
actor 用户
rectangle 售后{
用户-->(创建退货单)
   创建退货单--> (MQ-生产-退货单已创建)
用户-->(取消退货单)
  取消退货单 --> (MQ-生产-退货单已取消)


用户-->(创建换货单)
  创建换货单 --> (MQ-生产-换货单已创建)

用户-->(取消换货单)
  取消换货单-->  (MQ-生产-换货单已取消)

用户-->(支付换货单)

用户-->(创建维修单)
  创建维修单-->  (MQ-生产-维修单已创建)

用户-->(取消维修单)
  取消维修单 --> (MQ-生产-维修单已取消)

用户-->(支付维修单)


用户-->(创建物流补发单)
  创建物流补发单-->  (MQ-生产-补发单已创建)

用户-->(取消物流补发单)
  取消物流补发单 --> (MQ-生产-补发单已取消)


用户-->(创建物流还款单)
 创建物流还款单 -->  (MQ-生产-物流还款单已创建)

用户-->(取消物流还款单)
  取消物流还款单-->  (MQ-生产-物流还款单已取消)



用户-->(检索售后单)
用户-->(查看售后单详情)
}


actor 售后单付款消息

rectangle 售后单{
售后单付款消息 -->(换货单付付款完成)
   换货单付付款完成-->(MQ-生产-换货单已支付)
   换货单付付款完成-->(创建换货发货单)
售后单付款消息 -->(维修单付付款完成)
    维修单付付款完成-->(MQ-生产-维修单已支付)

}


newpage
left to right direction
actor 售后单定时器
rectangle 售后单{
售后单定时器-->(推送换货发货单)
售后单定时器--->(推送补发发货单)
}
rectangle 售后单{
客服-->(检索售后单)
客服-->(创建售后单)
客服-->(取消售后单)
客服-->(查看售后单)
}

newpage
left to right direction

actor 客服
rectangle 退款单{
客服-->(PAYPAL账号生成退款单)
客服-->(降价生成退款单)
客服-->(修改退款单)

客服-->(检索退款单)
客服-->(审核退款单)
客服-->(查看退款单)
客服-->(重新申请退款)




客服-->(发起退款)
     发起退款-->(取消订单退款成功)
     发起退款-->(包裹拒收退款成功)
     发起退款-->(包裹丢失退款成功)
     发起退款-->(重复付款退款成功)
     发起退款->(退货退款成功)
           退货退款成功-->(MQ-生产-退货单已完成)
     发起退款-->(拒保退款成功)
     发起退款-->(降价退款成功)
     发起退款-->(物流还款退款成功)
            物流还款退款成功-->(MQ-生产-物流还款单已完成)
     发起退款-->(以旧换新退款成功)
     发起退款-->(PayPel账号退款成功)
     发起退款-->(作废付款退款成功)
}


newpage

actor 审计
审计 -->(审核0元单)
审计 -->(导出订单)

actor 运营
运营 -->(导入第三方Pop订单)



newpage
left to right direction
actor 售后单发货单消息
rectangle 售后单发货单货单 {
  售后单发货单消息 ->(补发发货单已出库)
    补发发货单已出库-->(MQ-生成-补发单已完成)
    补发发货单已出库-->(计算补发履约结果)

  售后单发货单消息-->(换货返货单已出库)
    换货返货单已出库-->(MQ-生产-换货单已完成)
    换货返货单已出库-->(计算换货履约结果)

}
newpage
left to right direction
actor RMA消息
rectangle RMA{
    RMA消息 --->(换货RMA已取消)
    RMA消息 --->(换货RMA已通过)
    RMA消息 -->(换货RMA的商品已收到)
    RMA消息 ->(换货RMA的报价)
    RMA消息 ->(换货RMA已完成)
        换货RMA已完成-->(计算换货履约结果)

    RMA消息 ->(退货RMA已取消)
    RMA消息 -->(退货RMA已通过)
    RMA消息 -->(退货RMA的商品已收到)
    RMA消息 ->(退货RMA已检测完成)
        RMA消息 ->(生成退货退款单)
    RMA消息 ->(退货RMA已完成)
        退货RMA已完成-->(计算退货履约结果)

    RMA消息 -->(维修RMA已取消)
    RMA消息 -->(维修RMA已通过)
    RMA消息 -->(维修RMA的商品已收到)
    RMA消息 -->(维修RMA的报价)
    RMA消息 -->(维修RMA已完成)
        维修RMA已完成-->(计算维修履约结果)

    RMA消息 ->(补发RMA已取消)
    RMA消息 ->(补发RMA已通过)
    RMA消息 ->(补发RMA已处理)
        补发RMA已处理 -->(创建补发发货单)

    RMA消息 ->(物流还款RMA已取消)
    RMA消息 ->(物流还款RMA已通过)
        物流还款RMA已通过 -->(物流异常生成退款单)
}
newpage
left to right direction
actor 保险消息
rectangle 保险{
    保险消息 -->(保险拒保)
    保险消息 -->(保险使用)
    保险拒保-->(保险拒保生成退款单)
    保险拒保-->(更新保险履约)
    保险使用-->(更新保险履约)

}
newpage
left to right direction
actor 国内发票消息
rectangle 国内发票{
 国内发票消息-->订单发票纸质转电子票
 国内发票消息-->订单发票电子票转无效
 国内发票消息-->订单发票电子票转纸质
 国内发票消息-->订单发票更新
}



@endnuml