@startuml
Oridinate -> Actor1:询问是否可以提交事务
Oridinate -> Actor2:询问是否可以提交事务
Oridinate -> Actor3:询问是否可以提交事务

Oridinate <- Actor1:OK
Oridinate <- Actor2:OK
Oridinate <- Actor3:OK

Oridinate -> Actor1:发出commit请求
Oridinate -> Actor2:发出commit请求
Oridinate -> Actor3:发出commit请求

Actor1  -> DB1:提交事务,记录事务日志
Actor2  -> DB2:提交事务,记录事务日志
Actor3  -> DB3:提交事务,记录事务日志

Oridinate <- Actor1:ACK
Oridinate <- Actor2:ACK
Oridinate <- Actor3:ACK

newpage
Oridinate -> Actor1:询问是否可以提交事务
Oridinate -> Actor2:询问是否可以提交事务
Oridinate -> Actor3:询问是否可以提交事务

Oridinate <- Actor1:OK
Oridinate <- Actor2:OK
Oridinate <- Actor3:OK

Oridinate -> Actor1:发出commit请求
Oridinate -> Actor2:发出commit请求
Oridinate -> Actor3:发出commit请求

Actor1  -> DB1:提交事务,记录事务日志
Actor2  -> DB2:提交事务,记录事务日志
Actor3  -> DB3:提交事务,记录事务日志

Oridinate <- Actor1:ACK
Oridinate <- Actor2:提交失败
Oridinate <- Actor3:ACK

Oridinate -> Actor1:回滚请求
Oridinate -> Actor2:回滚请求
Oridinate -> Actor3:回滚请求

Actor1  -> DB1:回滚事务
Actor2  -> DB2:回滚事务
Actor3  -> DB3:回滚事务

Oridinate <- Actor1:ACK
Oridinate <- Actor2:ACK
Oridinate <- Actor3:ACK
@enduml