@startuml
title 三阶段事务提交时序图
== 阶段一 ==
Oridinate -> Actor1:canCommit请求，是否可以执行事务操作
Oridinate -> Actor2:canCommit请求，是否可以执行事务操作

Oridinate <- Actor1:YES
Oridinate <- Actor2:YES

== 阶段二 ==
Oridinate -> Actor1:发出preCommit请求
Oridinate -> Actor2:发出preCommit请求

Actor1  -> DB1:执行事务,记录事务日志
Actor2  -> DB2:执行事务,记录事务日志

Oridinate <- Actor1:ACK
Actor1 -> Actor1:阻塞等待最终指令\n(commit or abort)
Oridinate <- Actor2:ACK
Actor2 -> Actor2:阻塞等待最终指令\n(commit or abort)

== 阶段三 ==
Oridinate -> Actor1:发送doCommit请求 or <font color=red><b>接收协调者指令超时
Oridinate -> Actor2:发送doCommit请求 or <font color=red><b>接收协调者指令超时

Actor1  -> DB1:commit事务
Actor2  -> DB2:commit事务

Oridinate <- Actor1:ACK
Oridinate <- Actor2:ACK
@enduml