@startuml
hide member
class 售后商品{
    售后商品详情Id
    售后商品详情编号
    换货单原商品详情编号
    售后受理单编号
    售后类型
    商品编码
    商品名称
    商品数量
    分类ID
    商品原价
    商品销售价
    商品特惠价
    修改时间
    创建时间
    参与活动优惠的总金额
    套装时活动对应的图片
    套装描述
    套装说明
    商品类型
    是否有延保
    保修到期时间
    是否有意外保
    意外保到期日
    商品自身保修月数
    退换修原因
    检测状态
    检测通过数量
    检测不通过数量
    wms检测不通过原因
    是否允许退货
    退货天数
    是否允许换货
    换货天数
    是否允许维修
    维修天数
    手机IMEI号
    售后更换的最新的imei号
    售后更换的最新的imei号对应的订单号
}

class 退货受理单{
    退货受理单ID
    退货受理单编码
    关联的源退货订单Code
    换货订单编号
    网点编号
    库房地址编号
    退货受理单类型
    退货方式
    审核人ID
    审核时间
    退货原因
    退货商品数量
    应退款金额
    折旧维修单产生的折扣金额
    已使用、已过期的保险金额
    运费
    剩余商品无运费的总价
    活动总优惠金额
    原总价
    剩余商品金额
    保险金额
    成功退款的历史折旧总金额
    历史保险金额
    历史成功退款的累加总金额
    实退款金额
    原订单总金额
    原订单优惠总金额
    订单合约金额
    手机号码金额
    创建人
    创建时间
    修改人
    修改时间
    退货受理单取消时间
    退货受理单取消人Id
    退货受理单取消原因
    折旧维修单号
    退货发件人地址编号
    用户ID
    配送时段
    预约时间
    受理单来源类型
    服务类型
    服务类型原因
    客服审核受理单类型
    分配人
    手动退款金额
    手动退款运费
}

class 维修受理单{
    主键
    受理单编号
    订单编号
    维修单编号
    网点编号
    是否有延保
    保修到期日
    来源渠道
    购买渠道
    受理单状态
    检查人
    检查时间
    维修原因
    结束时间
    创建人
    创建时间
    更新人
    更新时间
    取消人
    取消时间
    取消原因
    备注
    预约日期
    地址编号
    用户ID
    受理单来源类型
    服务类型
    是否为第三方售后
    外部订单时间
    服务类型原因
    客服审核受理单类型
    分配人
    第三方售后imei
}

class 维修处理单{
    主键
    网点编号
    订单编号
    维修单编号
    受理单编号
    是否有意外保
    意外保到期时间
    维修单状态
    总费用
    总数量
    支付时间
    检测时间
    创建人
    创建时间
    更新人
    更新时间
    取消人
    取消时间
    取消原因
    备注
    维修原因
    用户ID
    预约日期
    检测结果
    服务类型
    是否为第三方售后
}

class 换货受理单{
    受理单id
    换货受理单号
    换货受理单类型
    网点编号
    状态
    原单编号
    换货订单编号
    退货单号
    备货单号
    折扣维修单号
    来源类型
    购买渠道
    库房地址编号
    换货单收获地址id
    审核人工号
    审核时间
    创建人
    创建时间
    修改人
    修改时间
    取消人
    换货单取消时间
    换货单取消原因
    预约时间
    备注
    用户ID
    配送时段
    退货原因
    用户中心地址主键
    受理单来源类型
    服务类型
    是否为第三方售后
    附件链接
    外部订单时间
    服务类型原因
    客服审核受理单类型
    分配人
}

class 售后地址{
    地址Id
    用户中心地址主键
    地址编号
    收货人姓名
    固定电话
    移动电话
    省ID
    省
    市ID
    市
    区ID
    区
    街道ID
    街道地址
    邮编
    创建时间
    修改时间
    买家ID
    详细地址
    业务单据号
    业务类型
}

class 退货处理单{
    退货单ID
    退货单编码
    退货受理单编码
    换货订单编号
    手机串号
    退货单状态
    退货单类型
    创建人
    创建时间
    修改人
    修改时间
    退货单取消人Id
    退货单取消时间
    退货单取消原因
    检测人ID
    检测时间
    快递单号
    用户ID
    关联的源退货订单Code
    折旧维修单
    检测状态
    退款状态
    退款状态
    备注
    网点检测备注
    服务类型
}

class 网点处理单{
    处理单ID
    随机附件
    客户意见
    取消原因
    客户ID
    报修人电话号码
    报修人姓名
    折扣金额
    工程师
    处理备注内容
    处理时间
    处理方式
    新IMEI号码
    IMEI号码
    初检备注
    检测结果
    故障描述
    订单编号
    取机备注
    取机时间
    取机人
    发票号码
    接单时间
    接单人员
    复检时间
    预约时间
    递送人
    递送人电话号码
    受理网点编号
    软件版本
    来源ID
    来源类型
    状态
    外观描述
    报价总额
    处理单类型
    受理时间
    一级超时原因
    二级超时原因
    邮件已通知标记
    初检时间
    处理方案
    修改时间
    修改人
    服务类型
    创建人
    创建时间
    是否第三方
    维修级别
    结算金额
    物流公司名称
    商品邮寄给网点物流单号
    运单号
    商品邮寄给网点物流单号
}

class 网点处理单商品{
    主键ID
    创建时间
    商品编号
    新IMEI号码
    原IMEI号码
    最后修改时间
    订单编号
    所属处理单编号
    保险ids
    故障编号
    维修编号
    旧IMEI2
    新IMEI2
}

class 售后领退料申请单{
    申请单ID
    领退申请类别
    创建申请时间
    创建申请人
    最后修改时间
    最后修改人
    网点编码
    状态
    所属处理单
}

class 售后领退料申请单商品{
    主键ID
    创建时间
    商品编号
    新IMEI号码
    原IMEI号码
    最后修改时间
    订单编号
    所属处理单编号
    保险ids
    故障编号
    维修编号
    旧IMEI2
    新IMEI2
}

退货受理单..> 售后地址:dependent
换货受理单..> 售后地址:dependent
维修受理单..> 售后地址:dependent
退货受理单..> 售后商品:dependent
换货受理单..> 售后商品:dependent
维修受理单..> 售后商品:dependent

退货受理单-->退货处理单
维修受理单-->维修处理单

换货受理单-->网点处理单
退货处理单-->网点处理单
维修处理单-->网点处理单

网点处理单-left..>网点处理单商品
网点处理单-right..>售后领退料申请单
售后领退料申请单-right..>售后领退料申请单商品

@enduml