@startuml
class Thread{
    ThreadLocal.ThreadLocalMap threadLocals;
}
class ThreadLocal{
    protected T initialValue();
}
class ThreadLocalMap{

}
class WeakReference<ThreadLocal> {

}
class Entry{
    Object value;
    Entry(ThreadLocal k, Object v);
}

WeakReference <|-- Entry

ThreadLocalMap *-> Entry
ThreadLocalMap --> ThreadLocal
Thread *-> ThreadLocalMap
ThreadLocal -> Thread

@enduml