@startuml
actor User
participant StorePage as pageInfo
participant XMAN as xman
participant TradeCenter as tc
participant WMS as wms
participant Inventory as inv
participant Redis as redis
participant ThirdWarehouse as warehouse

'->	同步消息
'<–	同步应答
'->>	异步消息
'<<-	异步应答

title ETD/ETA相关
==海外下单流程==
User        ->  pageInfo:<font color=red><b>[1] </font>点击进入商品列表页面
User        ->  pageInfo:<font color=red><b>[2] </font>Select商品
User        ->  pageInfo:<font color=red><b>[3] </font>点击CheckOut
User        ->  pageInfo:<font color=red><b>[4] </font>CheckOut页面：选择ShippingAddress
activate pageInfo
pageInfo    ->  xman    :ShippingAddress&Store
note right
通过ShippingAddress和UserSession调用用户中心
end note
xman        ->  inv     :地址信息&商品信息
xman        <-  inv     :路由信息&<font color=red>路由ETD/路由ETD
xman        <-  xman    :保存路由信息&<font color=red>路由ETD/路由ETD</font>到session
note right
注：用户登录Session过期时间为3d；
    ETD/ETA保存在session过期时间为1d
end note
pageInfo    <-  xman    :路由信息&<font color=red>路由ETD/路由ETD
pageInfo    <-  pageInfo:展示不同ShippingMethod的<font color=red>路由ETD/路由ETD
deactivate pageInfo

User        ->  pageInfo:<font color=red><b>[5] </font>CheckOut页面：选择ShippingMethod
User        ->  pageInfo:<font color=red><b>[6] </font>CheckOut页面：Place Order

activate pageInfo
pageInfo    ->  xman    :用户信息&商品信息

xman        ->  xman    :从session取出<font color=red>ETD/ETA</font>(路由信息),组装商品信息
xman        ->  tc      :商品信息，路由信息调用tc的dubbo接口
tc          -[#0000FF]>  inv     :预扣库存
activate tc
inv         -[#0000FF]>  redis     :获取仓库订单汇总信息
inv         -[#0000FF]>  inv       :计算原始ETD
inv         -[#0000FF]>  redis     :保存此订单信息到仓库订单汇总
deactivate tc
inv         ->  tc      :原始<font color=red>ETD/ETA
tc          ->  tc      :组装商品信息/路由信息<font color=red>ETD/ETA
tc          ->  redis   :保存商品信息，路由信息<font color=red>ETD/ETA</font>到redis
note right
此处保存到redis中的ETD/ETA为预占返回的原始ETD/ETA
而不是选择ShippingAddress返回的ETD/ETA
end note
pageInfo    <-  xman    :Place Order Successful

deactivate pageInfo

'tc          --[#0000FF]>  redis   :拉取订单信息(Schedule)
'note right
'线上5台分片redis,11台TradeCenter应用
'redis配有监控
'end note
tc          ->  tc      :保存订单信息
User        ->  pageInfo:<font color=red><b>[7] </font>支付订单
activate pageInfo
pageInfo    ->  xman
xman        ->  tc      :更新订单信息
deactivate pageInfo
tc          ->>  wms     :推送订单信息(MQ)

wms        ->  wms      :保存订单信息
wms        ->  inv      :实占库存(Schedule)
activate wms
inv         -[#0000FF]>  redis     :获取仓库订单汇总信息
inv         -[#0000FF]>  inv       :计算ETD
inv         -[#0000FF]>  redis     :保存此订单信息到仓库订单汇总
deactivate wms
wms        <-  inv     :<font color=red>ETD/ETD
wms        -->> tc       :MQ通知<font color=red>ETD/ETA</font>等信息

wms         ->  warehouse     :推送到第三方仓库

==订单出库逻辑==
warehouse   ->  warehouse     :出库
warehouse   ->  wms     :物流信息
activate warehouse
wms         -[#0000FF]>   inv:保存此订单出库信息到仓库订单汇总
inv         -[#0000FF]>   redis:保存此订单出库信息到仓库订单汇总
wms         -->  tc      :MQ通知出库时间、物流信息等
deactivate warehouse
==取消订单逻辑==
User -> pageInfo:取消
pageInfo -> tc:取消
tc -> wms:取消
wms -> inv:释放预占/实占库存
activate wms
inv -> inv:释放库存
inv -[#0000FF]> redis:更新仓库订单汇总
deactivate wms

@enduml