@startuml
left to right direction
actor 物流人员

rectangle WMS {
    (wms定时任务实占)
    (取消WMS订单)
    (接收仓库出库回传)
}

rectangle Inventory {
    (计算路由信息)
    (预扣库存)
    (实占库存)
    (更新仓库订单汇总信息)
    (释放预扣/占用/实占库存)
    (计算ETD)
    (获取仓库订单汇总信息)
}


(wms定时任务实占) ..>(实占库存)

(实占库存) .[#0000FF].> (更新仓库订单汇总信息):<include>
(预扣库存) .[#0000FF].> (更新仓库订单汇总信息):<include>
(释放预扣/占用/实占库存) ..[#0000FF]> (更新仓库订单汇总信息):<include>
(接收仓库出库回传) .[#0000FF]> (更新仓库订单汇总信息):<include>
物流人员 --> (取消WMS订单)

(取消WMS订单) .> (释放预扣/占用/实占库存):<include>


(预扣库存) ..> (计算ETD)
(实占库存) ..> (计算ETD)
(计算路由信息) ..> (计算ETD)

(计算ETD)  .[#0000FF].> (获取仓库订单汇总信息):<include>
@enduml