@startuml
'Store -> inventory:查询库存状态(countryCode,skuList,logisticInventoryBusinessType)
'inventory -> inventory:查询inv_logistic_inventory,校验是否支持此logisticInventoryBusinessType
title 流程图-查询库存状态SalesInventoryQueryService.queryInventoryStatus
start
:官网发起请求;
note right
(参数为：countryCode,skuList,
    logisticInventoryBusinessType);
end note

:Inv校验是否支持此logisticInventoryBusinessType;
note right
查询inv_logistic_inventory
end note

:遍历sku列表判断是否为抢购模式;
note right
根据抢购状态rushState、
抢购支持的业务类型、
抢购支持的sku列表
这三个均在动态配置中
end note

:1.查询logisticInventoryBusinessType对应的逻辑库存类型
2.查询该逻辑库存类型支持的所有的库区;
note right
从inv_logistic_inventory查询对应的逻辑库存类型
从inv_inventory_map_detail查询所有的库区
end note

if (国家为海外) then (yes)
    :查询inv_warehouse_region筛选该国家支持的库区,
    并设置优先级;
    note right
    如果是海外根据countryCode
    筛选覆盖的库区
    end note
endif

:如果是海外B2C业务优先从inv_sku_logistic_inventory_country
获取逻辑库存编码;

if(是否为抢购SKU) then(yes)
    :从抢购分片redis中查询数量;
    note left
        redis数据结构为String
        redisKey为
        inv:rush:stock:combineKey
        value为数量
    end note
else (no)
    :从缓存redis中获取;
    note right
        redis数据结构为String
        redisKey为INVC_INVCSTATUS
        SkuInventoryStatusDTO.toJsonStr()
    end note
endif

:合并两种类型的SkuInventoryStatusDTO;
end
@enduml