@startuml
title Facade Design Pattern Sequence Diagram
actor client as client
participant Facade as facade
participant "Module A" as A
participant "Module B" as B
participant "Module B" as C
note over of client #grey : 面向客户的客户端
note left of facade: 多个模块对外的高层接口
autonumber
client -> facade: 调用外观Facade的某个方法
note left : 由Facade来调用各个子模块
' Bob --> Alice: Authentication Response
facade -> A: 可能调用模块A
A -> B
A --> facade : fahui
'facade -> B: 可能调用模块B
'facade -> C: 可能调用模块C
autonumber 5
facade --> client : 返回结果


legend center
    此处为图形图例，居中对齐
endlegend

/'newpage 这是标题
 Bliss -> Tia : Let's go home
 Bliss -> Tia : Quick
  Tia -> Bliss : Give me money
  Tia -> Bliss : No money No love'/

@enduml