@startuml
participant "ReferenceConfig"         as ReferenceConfig
participant "AbstractProxyFactory"       as AbstractProxyFactory
participant "JdkProxyFactory"       as JdkProxyFactory
participant "InvokerInvocationHandler"       as InvokerInvocationHandler

ReferenceConfig->AbstractProxyFactory:getProxy(invoker)
AbstractProxyFactory->AbstractProxyFactory:getProxy(invoker,interfaces)
AbstractProxyFactory->JdkProxyFactory:getProxy(invoker,interfaces)
JdkProxyFactory->ReferenceConfig:ref
ReferenceConfig->JdkProxyFactory:ref.getBean("xxx")
JdkProxyFactory->InvokerInvocationHandler:invoke(ref,method,args)

@enduml