@startuml
left to right direction

rectangle wms {
    (接收逆向入库)
    (更新逆向入库)
    (接收订单)
    (通知海外订单状态变化)
    (接收采购订单)
    (通用出库)
    (通用入库)
    (取消订单)
    (锁定订单)
    (接收退款信息)
    (查询订单)
    (接收B2B订单)
    (取消B2B订单)
    (通知国内B2B订单状态变更)
    (通知海外B2B订单状态变更)
    (业务单据写入ERP)
    (查询保险)
    (查询IMEI)
    (查询业务单据)
}

rectangle erpadmin {
    (同步采购订单)
    (查询个人物料)
    (记录个人物料)

    (同步数据至ERP)
    (同步数据至OA)
    (查询ERP数据)
    (接收业务单据)
}

rectangle oa {
    (部门领料) --> (国内领料):include
    (部门领料) --> (海外领料):include
    (部门退料) --> (海外退料):include
    (部门退料) --> (国内退料):include
}

rectangle cs {
    (推送逆向入库) --> (推送国内逆向入库):include
    (推送逆向入库) --> (推送海外逆向入库):include

    (通知WMS退款金额) --> (通知国内RMA退款):include
    (通知WMS退款金额) --> (通知海外RMA退款):include

    (更新WMS逆向入库单) --> (更新国内WMS逆向入库单):include
    (更新WMS逆向入库单) --> (更新海外WMS逆向入库单):include

    (查询WMS订单) --> (查询海外WMS订单)
    (查询WMS订单) --> (查询国内WMS订单)

    (备件领退料)
    (维修出入库)
    (报废)
    (借转销)

}

rectangle xman {
    (推送海外订单)
    (接收海外订单状态变化通知)
    (取消海外订单)
    (Hold订单)
}

rectangle opss {
    (推送国内B2B订单)
    (推送海外B2B订单)
    (取消国内B2B订单)
    (取消海外B2B订单)
    (接收国内B2B订单状态变更)
    (接收海外B2B订单状态变更)
}

rectangle km {
    (查询WMS保险) -up-> (查询国内保险):include
    (查询WMS保险) -up-> (查询海外保险):include
    (查询WMS IMEI) -up-> (查询国内IMEI):include
    (查询WMS IMEI) -up-> (查询海外IMEI):include
}

rectangle user {
    (IMEI认证) -up-> (国内IMEI认证):include
    (IMEI认证) -up-> (海外IMEI认证):include
}

rectangle inv {
    (流水核查) --> (国内流水核查):include
    (流水核查) --> (海外流水核查):include
}

rectangle 外部系统 {
    (aftership)
    (WS系统回传出库信息)
    (Delivery系统回传出库信息)
}

(推送海外订单) -up-> (接收订单)
(通知海外订单状态变化) -up-> (接收海外订单状态变化通知)
(取消海外订单) -up-> (取消订单)
(Hold订单) -up-> (锁定订单)

(海外领料) --> (通用出库)
(海外退料) --> (通用入库)
(国内领料) --> (通用出库)
(国内退料) --> (通用入库)

(通用出库) --> (记录个人物料)
(通用入库) --> (记录个人物料)

(推送国内逆向入库) --> (接收逆向入库)
(推送海外逆向入库) --> (接收逆向入库)
(通知国内RMA退款) --> (接收退款信息)
(通知海外RMA退款) --> (接收退款信息)
(更新国内WMS逆向入库单) --> (更新逆向入库)
(更新海外WMS逆向入库单) --> (更新逆向入库)
(查询海外WMS订单) --> (查询订单)
(查询国内WMS订单) --> (查询订单)

(国内流水核查) --> (查询业务单据)
(海外流水核查) --> (查询业务单据)


(推送国内B2B订单) --> (接收B2B订单)
(推送海外B2B订单) --> (接收B2B订单)
(取消国内B2B订单) --> (取消B2B订单)
(取消海外B2B订单) --> (取消B2B订单)
(通知海外B2B订单状态变更) --> (接收海外B2B订单状态变更)
(通知国内B2B订单状态变更) --> (接收国内B2B订单状态变更)

(接收采购订单) <-- (同步采购订单)
(业务单据写入ERP) --> (接收业务单据)

(查询国内保险) -up-> (查询保险)
(查询海外保险) -left-> (查询保险)
(查询国内IMEI) -left-> (查询IMEI)
(查询海外IMEI) -left-> (查询IMEI)

(国内IMEI认证) -up-> (查询IMEI)
(海外IMEI认证) -up-> (查询IMEI)

@enduml