@startuml
'skinparam backgroundColor LightYellow
'-4预占失败 -3待预占 -2实占失败 -1待实占,0已分配库存,
'1已分配拣货单,2已打印,3已领单,4已拣货完成,5配货完成,
'6已打包,8已扫描,9待出库,7已出库'


state 发货单状态 {
    [*] -> 待预占:抢购订单/后台单
    [*] -down-> 待分配实存 :普通订单
    待预占 --> 待分配实存 :预占成功
    待预占 -right-> 预占失败 :预占失败
    预占失败 --> 待分配实存 :预占成功
    待分配实存 -down-> 已分配实存 : 分配实存成功
    待分配实存 -down-> 实存分配失败 : 分配实存失败
    实存分配失败 -right-> 已分配实存 : 分配实存成功
    已分配实存 -down-> 已出库 : 订单出库
}
state 自建仓发货单状态 {
    已分配实存 -down-> 已分配拣货单 : 制单
    已分配拣货单 -down-> 已打印 : 打印购物清单和发票
    已打印 -down-> 已领单 : 领取拣货单
    已领单 -down-> 已拣货完成 : 拣货
    已拣货完成 -left-> 配货完成 : 配货
    配货完成 -up-> 已打包 : 打包
    已打包 -up-> 已扫描 : 扫描出库
    已扫描 -up-> 待出库 : 完成扫描
    待出库 -left-> 已出库 : 确认出库
}


state 推送状态 {
    [*] --> 待推送 :第三方仓库
    [*] -> 无需推送 :自建仓库
    待推送 -> 已推送 :推送第三方成功
    待推送 --> 推送失败 :推送第三方失败
    推送失败 --> 已推送 :推送第三方成功
    无需推送 -> [*]
    已推送 --> [*]
}

state 有效状态{
    [*] --> 有效 :接收订单
    有效 -> 无效 :取消订单
}

state 锁定状态{
    [*] --> 未锁定 :接收订单
    未锁定 -> 锁定 :hold订单
    锁定 -> 未锁定 :unHold订单
}

state 路由状态 {
    [*] --> 未签收 :订单出库
    未签收 --> 已签收 :订单出库
}
@enduml