@startuml
actor Time
control trade
control wms
control inv
autonumber 10 10 "<b>[000]"
trade -> wms: 推送订单

alt 抢购订单
    Time --> wms: 定时路由和预占库存
    wms --> inv: 路由和预占库存
else 无
end
Time --> wms: 定时占用实存
wms --> inv: 占用实存
wms --> trade: 通知状态变更：已分配实存


control erp
boundary 第三方物流系统 as Logistic
actor 制单员 as invoicer
actor 仓管员 as warehouser

invoicer --> wms: 生成拣货批次
alt 纸质发票
    invoicer --> wms: 打印纸质发票
else 电子发票
end
warehouser --> wms: 打印购物清单
warehouser --> wms: 拣货
wms --> wms: 更新状态
warehouser --> wms: 配货
wms --> wms: 更新状态
warehouser --> wms: 打包
wms --> Logistic: 获取运单号
wms --> wms: 打印物流面单
wms --> wms: 更新状态
warehouser --> wms: 出库
wms --> wms: 更新状态

wms --> inv: 扣减库存
wms --> erp: 记录订单发货和账目信息
wms --> trade: 通知订单发货信息

@enduml