@startuml
actor 用户
用户 -> 商城: 退货售后申请 \n 1、RMA核心信息 \n 2、RMA地址 \n 3、RMA商品明细
商城 -> GSP:推送售后申请到GSP
GSP->GSP:校验RMA申请参数 \n 1、订单号必填 \n 2、RMA地址必填 \n 3、RMA商品明细不为空
actor 呼叫中心客服
actor 网点
GSP->SCM:根据订单号查询订单详情
SCM-->GSP:返回订单详情
GSP->GSP:校验订单信息 \n 1、订单存在SCM \n 2、订单非大订单类型 \n 3、订单状态是已发货
GSP->GSP:计算当前订单对应的SKU的可退数量
alt SKU申请售后数量大于可退数量
    GSP->GSP:提示可退数量不足异常
else SKU申请售后数量小于或者等于可退数量
    GSP->GSP:保存RMA申请单
end
呼叫中心客服->GSP:审核RMA信息操作
alt 取消
    GSP->GSP:更新RMA为已取消
else 审核 \n 1、编辑完善RMA申请信息 \n 2、选择网点,派单RMA到网点
        GSP->GSP:更新RMA待网点接受
        网点->GSP:RMA接受受理操作
        GSP->GSP:更新RMA为网点待入库
        网点->GSP:RMA入库操作
        alt 网点RMA申请取消
        loop
            GSP->GSP:更新RMA为申请取消
            呼叫中心客服->GSP:RMA取消、拒绝操作
                alt RMA取消
                    GSP->GSP:更新RMA已取消状态
                else RMA拒绝
                    GSP->GSP:更新RMA为网点待入库
                end
        end
        else 网点RMA入库
            GSP->GSP:更新RMA为已入库
        end
        网点->GSP:RMA检测操作
        GSP->GSP:更新RMA为检测中
        网点->GSP:结束检测操作
        GSP->GSP:更新RMA为检测结束
        alt 检测不通过
            网点->GSP:RMA打回操作
            GSP->GSP:保存寄回给用户物流信息
            GSP-->物流服务商:RMA物流对接(线下)
            GSP->GSP:更新RMA为已退货拒收状态
        else 检测通过
            网点->GSP:申请退款操作
            GSP->GSP:更新RMA为等待退款状态
            GSP->GSP:生成RMA待审核状态的退款单

            呼叫中心客服->GSP:审核退款单操作
            alt 审核
                呼叫中心客服->GSP:退款操作
                GSP->支付:调用退款接口
                支付-->GSP:返回成功
                GSP->GSP:更新退款单为已完成
                GSP->GSP:更新RMA申请单为已完成
                GSP->SCM:逆向通知RMA
            else 拒绝
                GSP->GSP:更新退款单为已拒绝
                GSP->GSP:更新RMA申请单为检测结束
            end
        end
end
@enduml