@startuml
actor 用户
actor 呼叫中心客服

control 商城
control 订单中心 as trade
control GSP
control 支付
entity 物流服务商
actor 网点

autonumber 10 10 "<b>[000]"
用户 -> 商城: 退货售后申请
autonumber resume "<font color=red><b>[000]"
商城 -> trade: 记录售后申请
trade -> trade: 校验申请参数
trade -> trade: 校验订单信息和可退数量
trade -> GSP:推送售后申请

autonumber resume "<b>[000]"

呼叫中心客服 -> GSP:审核RMA信息操作

alt 呼叫中心客服取消
    GSP -> GSP:更新RMA为已取消
    autonumber resume "<font color=red><b>[000]"
    GSP -> trade: 通知trade变更
    autonumber resume "<b>[000]"
else 用户取消
    autonumber resume "<font color=red><b>[000]"
    trade->GSP:通知RMA更新状态为已取消
    autonumber resume "<b>[000]"
else 审核 \n 1、编辑完善RMA申请信息 \n 2、选择网点,派单RMA到网点
        GSP -> GSP: 更新RMA待网点接受
        网点 -> GSP: RMA接受受理操作
        GSP -> GSP: 更新RMA为网点待入库

        alt 网点申请取消RMA
            loop
                网点 -> GSP: 申请取消RMA
                GSP -> GSP:更新RMA为申请取消状态
                alt 客服同意取消
                    呼叫中心客服 -> GSP: 审核通过取消
                    GSP -> GSP:更新RMA已取消状态
                    autonumber resume "<font color=red><b>[000]"
                    GSP -> trade: 通知trade变更
                    autonumber resume "<b>[000]"
                else 客服不同意取消
                    呼叫中心客服 -> GSP: 拒绝取消
                    GSP -> GSP:更新RMA为网点待入库
                end
            end
        else 网点操作RMA入库
            网点 -> GSP: 操作RMA入库
            GSP -> GSP: 更新RMA为已入库
            autonumber resume "<font color=red><b>[000]"
            GSP -> SCM: 通知逆向预入库
            GSP -> trade: 通知trade状态变更
            autonumber resume "<b>[000]"
        end

        网点 -> GSP:RMA检测操作
        GSP -> GSP:更新RMA为检测中
        网点 -> GSP:结束检测操作
        GSP -> GSP:更新RMA为检测结束
        alt 检测不通过
            网点 -> GSP:RMA打回操作
            GSP -> GSP:保存寄回给用户物流信息
            GSP --> 物流服务商:RMA物流对接(线下)
            GSP -> GSP:更新RMA为已退货拒收状态
            autonumber resume "<font color=red><b>[000]"
            GSP -> trade: 通知trade变更
            GSP->SCM:取消逆向入库
            autonumber resume "<b>[000]"
        else 检测通过
            网点 -> GSP:申请退款操作
            GSP -> GSP:更新RMA为等待退款状态
            autonumber resume "<font color=red><b>[000]"
            GSP -> trade: 通知trade状态变更
            trade -> trade: 生成退款单
            呼叫中心客服 -> GSP:审核退款单操作
            GSP --> trade:审核退款单操作
            alt 审核
                trade -> 支付:调用退款接口
                trade -> trade:更新退款单状态为已完成
                trade -> GSP:通知RMA状态为已完成
                GSP -> SCM: 通知逆向实际入库
            else 拒绝
                trade -> trade:更新退款单状态为已拒绝
                trade -> GSP:通知RMA状态变更(状态待定)
            end
        end
end
@enduml