@startuml

class DeliveryPushMsg{
pushType 订单类型
}
class WmsPushBaseDTO{
    userId,
    userName,
    orderNo 订单号
}
class DeliveryPushDTO{
orderType 普通、抢购、第三方,
serviceOrderType,
orderChannel 订单渠道,
orderFrom 订单来源,
<font color=red>skuOriginAmount 订单Sku原始总金额,
skuDiscountAmount 订单Sku折扣总金额,
shippingOriginFee,
shippingNowFee,
taxFee,
<font color=red>orderTotalAmount,
shippingType 发货类型
}
class WmsPushRmaDTO
class AddressBillingDTO {
    bizNo 订单号
}
class AddressShippingDTO
class DeliveryOrderDTO{
    bizNo 发货单号,
    logisticsNo 物流单号,
    orderNo 关联订单号,
    warehouseCode 仓库,
    warehouseAreaCode 库区,
    shippingMethodCode 物流渠道,
    shippingType 发货单的实际发运方式,
    originEta,
    originEtd,
   <font color=red>deliveryAmount 发货单的总金额,
   <font color=red>deliveryOriginAmount 发货单的原始总金额
    deliveryDiscountAmount 发货单的折扣总金额
}
class DeliveryItemDTO{
itemId 订单项,
skuCode 商品编号
skuCount 商品数量
<font color=red>originPrice 商品原价
salePrice 商品算价的起价
nowPrice 商品现价
discountAmount 商品折扣总金额
}
DeliveryPushDTO <|-- DeliveryPushMsg
AddressShippingDTO <|-- DeliveryPushDTO
AddressBillingDTO <|-- DeliveryPushDTO
'DeliveryPushDTO <|-- DeliveryPushMsg
'WmsPushBaseDTO <|--WmsPushRmaDTO
'WmsPushOrderDTO<-- WmsPushDTO
'AddressBillingDTO<-- WmsPushBaseDTO
'AddressShippingDTO<-- WmsPushBaseDTO
DeliveryPushDTO*--> DeliveryOrderDTO
DeliveryOrderDTO*--> DeliveryItemDTO


'WmsPushDTO..> WmsPushOrderDTO

@enduml