@startuml
participant Schedule
participant ThreadPoolExecutor
participant Pools
participant Redis
database  DB



==同步流水到DB==
Schedule -> Pools:从所有分片redis中通过加权轮询策略获取一个分片，\n并获取该分片的jedis连接
activate Schedule
Pools -> Redis:获取指定分片的jedis连接
Redis -> Redis:从未同步流水list取出一条Logkey放入已同步list中
Schedule -> ThreadPoolExecutor:将取出的流水Logkey提交到线程池中
deactivate Schedule

ThreadPoolExecutor -> Redis: 通过Logkey中订单号路由到分片Redis
activate ThreadPoolExecutor
ThreadPoolExecutor -> Redis: 从redis中通过Logkey获取流水记录
ThreadPoolExecutor -> DB: 保存流水到数据库
ThreadPoolExecutor -> Redis: 从redis中已经同步队列删除Logkey
deactivate ThreadPoolExecutor
@enduml